// Программы школа 8 - 9 класс
export const school89: Program[] = [
  'mathSchool8',
  'physSchool8',
  'chemSchool8',
  'bioSchool8',
  'hisSchool8',
  'socSchool8',
  'rusSchool8',
  'litSchool8',
  'engSchool8',
  'infSchool8',
  'geoSchool8',
  'mathSchool9',
  'physSchool9',
  'chemSchool9',
  'bioSchool9',
  'hisSchool9',
  'socSchool9',
  'rusSchool9',
  'litSchool9',
  'engSchool9',
  'infSchool9',
  'geoSchool9',
  'physOgeSchool9',
  'chemOgeSchool9',
  'bioOgeSchool9',
  'hisOgeSchool9',
  'socOgeSchool9',
  'litOgeSchool9',
  'engOgeSchool9',
  'infOgeSchool9',
  'geoOgeSchool9',
] as const
