version: "3"
name: "ec"
services:
  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    networks:
      - internal
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - ../back/:/var/www/html/
      - nginx:/var/log/nginx/
  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    networks:
      - internal
    volumes:
      - ../back/:/var/www/html/
  mysql:
    image: mysql/mysql-server:8.0
    ports:
      - 3306:3306
    env_file: ./mysql/.env
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - internal
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - redis:/data
    networks:
      - internal
  crm:
    ports:
      - 3000:3000
    build: ./node
    volumes:
      - ../crm/:/crm

networks:
  internal:
    driver: bridge

volumes:
  nginx:
  mysql:
  redis:
