version: "3"
services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    networks:
      - internal
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - ../back/:/var/www/html/
      - ./logs/nginx:/var/log/nginx/
  php:
    # build:
    #   context: ./php
    #   dockerfile: Dockerfile
    #   args:
    #     WWWGROUP: "${WWWGROUP}"
    image: php:fpm-alpine
    networks:
      - internal
    volumes:
      - ../back/:/var/www/html/
  mysql:
    image: mysql/mysql-server:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - "sail-mysql:/var/lib/mysql"
      - "./docker/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh"
    networks:
      - internal
networks:
  internal:
    driver: bridge
