<script setup lang="ts">
const { $addSseListener, $removeSseListener } = useNuxtApp()
const { public: config } = useRuntimeConfig()
const { rememberUser, logIn } = useAuthStore()
const phone = ref('')
const phoneMask = { mask: '+7 (###) ###-##-##' }
const user = ref<AuthResource>()
const loading = ref(false)
const errors = ref<{
  phone?: ResponseErrors
  code?: ResponseErrors
}>({})
const otpInput = ref()
const phoneInput = ref()
const otp = reactive({
  code: '',
  error: false,
  loading: false,
})
const window = ref(rememberUser ? 1 : 0)

// QR generated by https://mini-qr-code-generator.vercel.app/
const bot = config.env === 'local'
  ? {
      url: 'https://t.me/ec_local_bot',
      qr: '/img/qr-auth-local.png',
    }
  : {
      url: 'https://t.me/egecentr_bot',
      qr: '/img/qr-auth.png',
    }

async function onPhoneEnter() {
  loading.value = true
  errors.value = {}
  const { data, error } = await useHttp<AuthResource>(
    `common/auth/login`,
    {
      method: 'post',
      body: {
        phone: phone.value,
      },
    },
  )
  setTimeout(() => (loading.value = false), 300)
  if (error.value) {
    errors.value = error.value.data.errors
    return
  }
  if (data.value) {
    user.value = data.value
    console.log(user.value)
    nextTick(() => {
      window.value = user.value?.telegram_id ? 3 : 2
    })
  }
}

function otherUser() {
  window.value = 0
  // setTimeout(() => (cookieUser.value = null), 1000)
}

function continueRememberMe() {
  if (rememberUser === undefined) {
    return
  }
  phone.value = rememberUser.number
  onPhoneEnter()
}

async function onOtpFinish() {
  errors.value = {}
  otp.loading = true
  const { data, error } = await useHttp<TokenResponse>(
    'common/auth/verify-code',
    {
      method: 'post',
      body: {
        phone: phone.value,
        code: otp.code,
      },
    },
  )
  if (error.value) {
    otp.loading = false
    errors.value = error.value.data.errors
    nextTick(() => otpInput.value.focus())
    return
  }
  if (data.value) {
    const { user, token } = data.value
    logIn(user, token)
  }
}

watch(
  () => window.value,
  (newVal, oldVal) => {
    console.log(`${oldVal} => ${newVal}`)
    if (newVal === 0) {
      setTimeout(() => phoneInput.value.focus(), 300)
    }
    if (newVal === 2) {
      $addSseListener('TelegramBotAdded', (u: AuthResource) => {
        if (user.value?.id === u.id) {
          onPhoneEnter()
        }
      })
    }
    if (newVal === 3) {
      setTimeout(() => otpInput.value.focus(), 300)
    }
  },
)

onUnmounted(() => $removeSseListener('TelegramBotAdded'))

definePageMeta({ layout: 'login' })
</script>

<template>
  <form class="login">
    <div class="login__logo">
      <img src="/img/app.svg">
    </div>
    <v-window v-model="window">
      <v-window-item>
        <v-text-field
          ref="phoneInput"
          v-model="phone"
          v-maska:[phoneMask]
          label="Телефон"
          :error-messages="errors.phone"
          @keydown.enter="onPhoneEnter()"
        />
        <v-btn
          color="primary"
          :loading="loading"
          block
          size="x-large"
          @click="onPhoneEnter()"
        >
          Войти
        </v-btn>
      </v-window-item>
      <v-window-item eager>
        <v-card v-if="rememberUser" variant="tonal">
          <template #title>
            {{ formatName(rememberUser) }}
          </template>
          <template #subtitle>
            {{ formatPhone(rememberUser.number) }}
          </template>
          <template #prepend>
            <UiAvatar
              :item="rememberUser"
              :size="63"
              class="mr-3"
            />
          </template>
        </v-card>
        <v-btn
          color="primary"
          :loading="loading"
          block
          size="x-large"
          @click="continueRememberMe()"
        >
          продолжить
        </v-btn>
        <div class="login__other">
          <span @click="otherUser()"> другой пользователь </span>
        </div>
      </v-window-item>
      <v-window-item eager>
        <div
          v-if="user"
          class="login__info"
        >
          <div class="login__info-title">
            {{ user.first_name }}, здравствуйте!
          </div>
          <div>
            Это ваш первый вход в ЛК. Для продолжения необходимо
            <a :href="bot.url">
              добавить бота в Telegram
            </a>
          </div>
          <div class="login__qr">
            <img :src="bot.qr">
          </div>
          <!-- <a href="https://t.me/egecentr_bot" target="_blank">
            <v-btn color="primary" block size="x-large"> Открыть Telegram </v-btn>
          </a> -->
        </div>
      </v-window-item>
      <v-window-item eager>
        <div class="login__info">
          <div class="login__info-title">
            Проверьте Telegram
          </div>
          <div>Введите код, который пришёл к вам в сообщения</div>
        </div>
        <v-otp-input
          ref="otpInput"
          v-model="otp.code"
          :disabled="otp.loading"
          :error="!!errors.code"
          :length="4"
          class="mt-5"
          width="240"
          @finish="onOtpFinish"
        />
        <v-btn
          color="primary"
          :loading="otp.loading"
          block
          size="x-large"
          @click="onOtpFinish()"
        >
          Войти
        </v-btn>
      </v-window-item>
      <!-- reverse transition fix -->
      <v-window-item />
    </v-window>
  </form>
</template>

<style lang="scss">
.login {
  background: rgba(white, 0.95);
  border-radius: 20px;
  width: 400px;
  // border: 2px solid rgba(255, 196, 35, 0.5);
  z-index: 2;
  scale: 1.05;
  & > .v-text-field {
    margin-bottom: 20px;
    // .v-field__outline {
    //   color: rgb(var(--v-theme-primary));
    //   label {
    //     color: rgba(
    //       var(--v-theme-on-background),
    //       var(--v-high-emphasis-opacity)
    //     ) !important;
    //   }
    // }
  }
  button {
    margin-top: 60px;
  }
  &__logo {
    text-align: center;
    padding: 30px 0;
    img {
      width: 90px;
    }
  }
  &__qr {
    margin-top: 40px;
    text-align: center;
    img {
      width: 150px;
    }
  }
  &__info {
    font-size: 20px;
    text-align: center;
    text-wrap: balance;
    &-title {
      font-weight: bold;
      margin-bottom: 20px;
    }
  }
  &__other {
    text-align: center;
    position: relative;
    width: 100%;
    top: 14px;
    span {
      cursor: pointer;
      color: rgb(var(--v-theme-gray));
      transition: color cubic-bezier(0.4, 0, 0.2, 1) 0.15s;
      &:hover {
        color: black;
      }
    }
  }
  .v-card__underlay {
    background: rgb(var(--v-theme-gray)) !important;
    // opacity: 1 !important;
  }
  .v-card-title {
    font-size: 18px !important;
  }
  .v-window {
    &-item {
      padding: 30px;
    }
  }
}
</style>
