export const ProgramLabel = {
  math9: '9 курсы МАТ',
  phys9: '9 курсы ФИЗ',
  chem9: '9 курсы ХИМ',
  bio9: '9 курсы БИО',
  his9: '9 курсы ИСТ',
  soc9: '9 курсы ОБЩ',
  rus9: '9 курсы РУС',
  lit9: '9 курсы ЛИТ',
  eng9: '9 курсы АНГ',
  inf9: '9 курсы ИНФ',
  geo9: '9 курсы ГЕО',
  math10: '10 курсы МАТ',
  phys10: '10 курсы ФИЗ',
  chem10: '10 курсы ХИМ',
  bio10: '10 курсы БИО',
  his10: '10 курсы ИСТ',
  soc10: '10 курсы ОБЩ',
  rus10: '10 курсы РУС',
  lit10: '10 курсы ЛИТ',
  eng10: '10 курсы АНГ',
  inf10: '10 курсы ИНФ',
  geo10: '10 курсы ГЕО',
  math11: '11 курсы МАТ',
  phys11: '11 курсы ФИЗ',
  chem11: '11 курсы ХИМ',
  bio11: '11 курсы БИО',
  his11: '11 курсы ИСТ',
  soc11: '11 курсы ОБЩ',
  rus11: '11 курсы РУС',
  lit11: '11 курсы ЛИТ',
  eng11: '11 курсы АНГ',
  inf11: '11 курсы ИНФ',
  geo11: '11 курсы ГЕО',
  mathSchool8: '8 школа МАТ',
  physSchool8: '8 школа ФИЗ',
  chemSchool8: '8 школа ХИМ',
  bioSchool8: '8 школа БИО',
  hisSchool8: '8 школа ИСТ',
  socSchool8: '8 школа ОБЩ',
  rusSchool8: '8 школа РУС',
  litSchool8: '8 школа ЛИТ',
  engSchool8: '8 школа АНГ',
  infSchool8: '8 школа ИНФ',
  geoSchool8: '8 школа ГЕО',
  mathSchool9: '9 школа МАТ',
  physSchool9: '9 школа ФИЗ',
  chemSchool9: '9 школа ХИМ',
  bioSchool9: '9 школа БИО',
  hisSchool9: '9 школа ИСТ',
  socSchool9: '9 школа ОБЩ',
  rusSchool9: '9 школа РУС',
  litSchool9: '9 школа ЛИТ',
  engSchool9: '9 школа АНГ',
  infSchool9: '9 школа ИНФ',
  geoSchool9: '9 школа ГЕО',
  physOgeSchool9: '9 школа ФИЗ ОГЭ',
  chemOgeSchool9: '9 школа ХИМ ОГЭ',
  bioOgeSchool9: '9 школа БИО ОГЭ',
  hisOgeSchool9: '9 школа ИСТ ОГЭ',
  socOgeSchool9: '9 школа ОБЩ ОГЭ',
  litOgeSchool9: '9 школа ЛИТ ОГЭ',
  engOgeSchool9: '9 школа АНГ ОГЭ',
  infOgeSchool9: '9 школа ИНФ ОГЭ',
  geoOgeSchool9: '9 школа ГЕО ОГЭ',
  mathSchool10: '10 школа  МАТ',
  physSchool10: '10 школа ФИЗ',
  chemSchool10: '10 школа  ХИМ',
  bioSchool10: '10 школа  БИО',
  rusSchool10: '10 школа РУС',
  litSchool10: '10 школа  ЛИТ',
  hisSchool10: '10 школа  ИСТ',
  socSchool10: '10 школа ОБЩ',
  engSchool10: '10 школа  АНГ',
  infSchool10: '10 школа  ИНФ',
  geoSchool10: '10 школа ГЕО',
  mathSchool11: '11 школа МАТ',
  physSchool11: '11 школа ФИЗ',
  chemSchool11: '11 школа ХИМ',
  bioSchool11: '11 школа БИО',
  hisSchool11: '11 школа ИСТ',
  socSchool11: '11 школа ОБЩ',
  rusSchool11: '11 школа РУС',
  litSchool11: '11 школа ЛИТ',
  engSchool11: '11 школа АНГ',
  infSchool11: '11 школа ИНФ',
  geoSchool11: '11 школа ГЕО',
  mathExternal: 'экстернат МАТ',
  physExternal: 'экстернат ФИЗ',
  chemExternal: 'экстернат ХИМ',
  bioExternal: 'экстернат БИО',
  hisExternal: 'экстернат ИСТ',
  socExternal: 'экстернат ОБЩ',
  rusExternal: 'экстернат РУС',
  litExternal: 'экстернат ЛИТ',
  engExternal: 'экстернат АНГ',
  infExternal: 'экстернат ИНФ',
  geoExternal: 'экстернат ГЕО',
  mathPract: 'практикум МАТ',
  physPract: 'практикум ФИЗ',
  chemPract: 'практикум ХИМ',
  bioPract: 'практикум БИО',
  hisPract: 'практикум ИСТ',
  socPract: 'практикум ОБЩ',
  rusPract: 'практикум РУС',
  litPract: 'практикум ЛИТ',
  engPract: 'практикум АНГ',
  infPract: 'практикум ИНФ',
  geoPract: 'практикум ГЕО',
  izl9: 'собеседование',
  soch11: 'сочинение',
  engSpoken: 'разговорный английский',
} as const

export const TelegramTemplateLabel = {
  reportPublished: 'отчёт отправлен',
  reportRead: 'отчёт прочитан',
  clientLessonStatus: 'опоздал/не пришёл',
}

export const ProgramShortLabel = {
  eng10: '10К-АНГ',
  bio10: '10К-БИО',
  geo10: '10К-ГЕО',
  inf10: '10К-ИНФ',
  his10: '10К-ИСТ',
  lit10: '10К-ЛИТ',
  math10: '10К-МАТ',
  soc10: '10К-ОБЩ',
  rus10: '10К-РУС',
  phys10: '10К-ФИЗ',
  chem10: '10К-ХИМ',
  engSchool10: '10Ш-АНГ',
  bioSchool10: '10Ш-БИО',
  infSchool10: '10Ш-ИНФ',
  hisSchool10: '10Ш-ИСТ',
  litSchool10: '10Ш-ЛИТ',
  mathSchool10: '10Ш-МАТ',
  chemSchool10: '10Ш-ХИМ',
  geoSchool10: '10Ш-ГЕО',
  socSchool10: '10Ш-ОБЩ',
  rusSchool10: '10Ш-РУС',
  physSchool10: '10Ш-ФИЗ',
  eng11: '11К-АНГ',
  bio11: '11К-БИО',
  geo11: '11К-ГЕО',
  inf11: '11К-ИНФ',
  his11: '11К-ИСТ',
  lit11: '11К-ЛИТ',
  math11: '11К-МАТ',
  soc11: '11К-ОБЩ',
  rus11: '11К-РУС',
  phys11: '11К-ФИЗ',
  chem11: '11К-ХИМ',
  engSchool11: '11Ш-АНГ',
  bioSchool11: '11Ш-БИО',
  geoSchool11: '11Ш-ГЕО',
  infSchool11: '11Ш-ИНФ',
  hisSchool11: '11Ш-ИСТ',
  litSchool11: '11Ш-ЛИТ',
  mathSchool11: '11Ш-МАТ',
  socSchool11: '11Ш-ОБЩ',
  rusSchool11: '11Ш-РУС',
  physSchool11: '11Ш-ФИЗ',
  chemSchool11: '11Ш-ХИМ',
  engSchool8: '8Ш-АНГ',
  bioSchool8: '8Ш-БИО',
  geoSchool8: '8Ш-ГЕО',
  infSchool8: '8Ш-ИНФ',
  hisSchool8: '8Ш-ИСТ',
  litSchool8: '8Ш-ЛИТ',
  mathSchool8: '8Ш-МАТ',
  socSchool8: '8Ш-ОБЩ',
  rusSchool8: '8Ш-РУС',
  physSchool8: '8Ш-ФИЗ',
  chemSchool8: '8Ш-ХИМ',
  eng9: '9К-АНГ',
  bio9: '9К-БИО',
  geo9: '9К-ГЕО',
  inf9: '9К-ИНФ',
  his9: '9К-ИСТ',
  lit9: '9К-ЛИТ',
  math9: '9К-МАТ',
  soc9: '9К-ОБЩ',
  rus9: '9К-РУС',
  phys9: '9К-ФИЗ',
  chem9: '9К-ХИМ',
  engSchool9: '9Ш-АНГ',
  engOgeSchool9: '9Ш-АНГ-ОГЭ',
  bioSchool9: '9Ш-БИО',
  bioOgeSchool9: '9Ш-БИО-ОГЭ',
  geoSchool9: '9Ш-ГЕО',
  geoOgeSchool9: '9Ш-ГЕО-ОГЭ',
  infSchool9: '9Ш-ИНФ',
  infOgeSchool9: '9Ш-ИНФ-ОГЭ',
  hisSchool9: '9Ш-ИСТ',
  hisOgeSchool9: '9Ш-ИСТ-ОГЭ',
  litSchool9: '9Ш-ЛИТ',
  litOgeSchool9: '9Ш-ЛИТ-ОГЭ',
  mathSchool9: '9Ш-МАТ',
  socSchool9: '9Ш-ОБЩ',
  socOgeSchool9: '9Ш-ОБЩ-ОГЭ',
  rusSchool9: '9Ш-РУС',
  physSchool9: '9Ш-ФИЗ',
  physOgeSchool9: '9Ш-ФИЗ-ОГЭ',
  chemSchool9: '9Ш-ХИМ',
  chemOgeSchool9: '9Ш-ХИМ-ОГЭ',
  engPract: 'ПР-АНГ',
  bioPract: 'ПР-БИО',
  geoPract: 'ПР-ГЕО',
  infPract: 'ПР-ИНФ',
  hisPract: 'ПР-ИСТ',
  litPract: 'ПР-ЛИТ',
  mathPract: 'ПР-МАТ',
  socPract: 'ПР-ОБЩ',
  rusPract: 'ПР-РУС',
  physPract: 'ПР-ФИЗ',
  chemPract: 'ПР-ХИМ',
  engSpoken: 'Р-АНГ',
  izl9: 'СОБЕС',
  soch11: 'СОЧ',
  engExternal: 'Э-АНГ',
  bioExternal: 'Э-БИО',
  geoExternal: 'Э-ГЕО',
  infExternal: 'Э-ИНФ',
  hisExternal: 'Э-ИСТ',
  litExternal: 'Э-ЛИТ',
  mathExternal: 'Э-МАТ',
  socExternal: 'Э-ОБЩ',
  rusExternal: 'Э-РУС',
  physExternal: 'Э-ФИЗ',
  chemExternal: 'Э-ХИМ',
} as const

export const BranchLabel = {
  ohr: 'ОХР',
  pvn: 'ВЕР',
  bgt: 'БАГ',
  izm: 'ИЗМ',
  opl: 'ОКТ',
  rpt: 'РЯЗ',
  skl: 'СКЛ',
  orh: 'ОРЕ',
  ann: 'АНН',
  per: 'ПЕР',
  klg: 'КЛЖ',
  brt: 'БРА',
  str: 'СТР',
  vld: 'ВЛА',
  bel: 'БЕЛ',
  bib: 'БИБ',
  svi: 'СВИ',
  nag: 'НАГ',
  sok: 'СОК',
  pla: 'ПЛА',
  vod: 'ВОД',
  trg: 'ТУР',
} as const

export const RequestStatusLabel = {
  new: 'новые',
  awaiting: 'в ожидании',
  finished: 'выполненные',
  trash: 'архив',
} as const

export const WeekdayLabel = {
  0: 'пн',
  1: 'вт',
  2: 'ср',
  3: 'чт',
  4: 'пт',
  5: 'сб',
  6: 'вс',
} as const

export const LessonStatusLabel = {
  planned: 'планируется',
  conducted: 'проведено',
  cancelled: 'отменено',
} as const

export const ClientLessonStatusLabel = {
  present: 'был',
  presentOnline: 'был дист',
  late: 'опоздал',
  lateOnline: 'опоздал дист',
  absent: 'не был',
} as const

export const QuarterLabel = {
  q1: '1 четверть',
  q2: '2 четверть',
  q3: '3 четверть',
  q4: '4 четверть',
  final: 'итоговая',
} as const

export const QuarterShortLabel = {
  q1: '1 четв.',
  q2: '2 четв.',
  q3: '3 четв.',
  q4: '4 четв.',
  final: 'итоговая',
} as const

export const MonthLabel = {
  1: 'январь',
  2: 'февраль',
  3: 'март',
  4: 'апрель',
  5: 'май',
  6: 'июнь',
  7: 'июль',
  8: 'август',
  9: 'сентябрь',
  10: 'октябрь',
  11: 'ноябрь',
  12: 'декабрь',
} as const

export const MonthLabelShort = {
  1: 'янв',
  2: 'фев',
  3: 'мар',
  4: 'апр',
  5: 'мая',
  6: 'июн',
  7: 'июл',
  8: 'авг',
  9: 'сен',
  10: 'окт',
  11: 'ноя',
  12: 'дек',
} as const

// export const MonthLabelDative = [
//   'января',
//   'февраля',
//   'марта',
//   'апреля',
//   'мая',
//   'июня',
//   'июля',
//   'августа',
//   'сентября',
//   'октября',
//   'ноября',
//   'декабря',
// ] as const

export const EntityTypeValue = {
  request: 'App\\Models\\Request',
  client: 'App\\Models\\Client',
  clientParent: 'App\\Models\\ClientParent',
  contract: 'App\\Models\\Contract',
  teacher: 'App\\Models\\Teacher',
  user: 'App\\Models\\User',
  group: 'App\\Models\\Group',
  report: 'App\\Models\\Report',
} as const

export const EntityTypeLabel = {
  'App\\Models\\Request': 'заявка',
  'App\\Models\\Client': 'клиент',
  'App\\Models\\ClientParent': 'родитель',
  'App\\Models\\Contract': 'договор',
  'App\\Models\\Teacher': 'преподаватель',
  'App\\Models\\User': 'администратор',
  'App\\Models\\Group': 'группа',
  'App\\Models\\Report': 'отчет',
} as const

export const LessonScoreLabel = {
  5: 'пять',
  4: 'четыре',
  3: 'три',
  2: 'два',
} as const

export const YearLabel = {
  2025: '2025–2026 уч. г.',
  2024: '2024–2025 уч. г.',
  2023: '2023–2024 уч. г.',
  2022: '2022–2023 уч. г.',
  2021: '2021–2022 уч. г.',
  2020: '2020–2021 уч. г.',
  2019: '2019–2020 уч. г.',
  2018: '2018–2019 уч. г.',
  2017: '2017–2018 уч. г.',
  2016: '2016–2017 уч. г.',
  2015: '2015–2016 уч. г.',
} as const

/* eslint-disable */
export const CabinetLabel = {
  cab428: "К-428",
  cab430: "К-430",
  cab432: "К-432",
  cab433: "К-433",
  cab434: "К-434",
  cab439: "К-439",
  cab407: "К-407",
  cab409: "К-409",
  cab412: "К-412",
  cab413: "К-413",
  cab414: "К-414",
  cab417: "К-417",
  cab418: "К-418",
  cab420: "К-420",
  cab422: "К-422",
  cab423: "К-423",
  cab424: "К-424",
  cab310: "К-310",
  cab312: "К-312",
  cab314: "К-314",
  cab316: "К-316",
  tur10: "ТУР-10",
  tur35: "ТУР-35",
  tur205: "ТУР-205",
  tur214: "ТУР-214",
  tur221: "ТУР-221",
  tur301: "ТУР-301",
  tur302: "ТУР-302",
  tur303: "ТУР-303",
  tur304: "ТУР-304",
  tur305: "ТУР-305",
  tur310: "ТУР-310",
  tur311: "ТУР-311",
  tur314: "ТУР-314",
  tur319: "ТУР-319",
  tur320: "ТУР-320",
  tur321: "ТУР-321",
  tur322: "ТУР-322",
  tur507: "ТУР-507",
  tur809: "ТУР-809"
} as const;
/* eslint-enable */

export const TeacherStatusLabel = {
  inactive: 'неактивен',
  active: 'ведет занятия сейчас',
  earlyReserve: 'ранний запас',
  lateReserve: 'поздний запас',
  usedToWork: 'ранее работал',
  interview: 'собеседование',
  closed: 'закрыт',
} as const

export const UserStatusLabel: { [key: number]: string } = {
  1: 'действующий сотрудник',
  0: 'больше не работает',
}

export const SubjectLabel = {
  math: 'математика',
  phys: 'физика',
  chem: 'химия',
  bio: 'биология',
  inf: 'информатика',
  rus: 'русский язык',
  lit: 'литература',
  soc: 'обществознание',
  his: 'история',
  eng: 'английский язык',
  geo: 'география',
  soch: 'сочинение',
} as const

export const SubjectLabelShort = {
  math: 'МАТ',
  phys: 'ФИЗ',
  chem: 'ХИМ',
  bio: 'БИО',
  inf: 'ИНФ',
  rus: 'РУС',
  lit: 'ЛИТ',
  soc: 'ОБЩ',
  his: 'ИСТ',
  eng: 'АНГ',
  geo: 'ГЕО',
  soch: 'СОЧ',
} as const

export const TeacherPaymentMethodLabel = {
  card: 'карта',
  cash: 'наличные',
  bill: 'счёт',
  mutual: 'взаимозачёт',
} as const

export const ContractPaymentMethodLabel = {
  card: 'карта',
  cash: 'наличные',
  bill: 'счёт',
  matcap: 'маткапитал',
} as const

export const ClientPaymentMethodLabel = {
  card: 'карта',
  cash: 'наличные',
} as const

export const CompanyLabel = {
  ooo: 'ООО',
  ip: 'ИП',
} as const

export const ExamLabel = {
  ogeMath: 'ОГЭ математика',
  ogePhys: 'ОГЭ физика',
  ogeChem: 'ОГЭ химия',
  ogeBio: 'ОГЭ биология',
  ogeEng: 'ОГЭ английский',
  ogeInf: 'ОГЭ информатика',
  ogeRus: 'ОГЭ русский',
  ogeLit: 'ОГЭ литература',
  ogeGeo: 'ОГЭ география',
  ogeHis: 'ОГЭ история',
  ogeSoc: 'ОГЭ обществознание',
  egeMathBase: 'ЕГЭ математика база',
  egeMathProf: 'ЕГЭ математика профиль',
  egePhys: 'ЕГЭ физика',
  egeChem: 'ЕГЭ химия',
  egeBio: 'ЕГЭ биология',
  egeEng: 'ЕГЭ английский',
  egeInf: 'ЕГЭ информатика',
  egeRus: 'ЕГЭ русский',
  egeLit: 'ЕГЭ литература',
  egeGeo: 'ЕГЭ география',
  egeHis: 'ЕГЭ история',
  egeSoc: 'ЕГЭ обществознание',
  engSpoken: 'Разговорный английский',
  izl9: 'Изложение 9 класс',
  soch11: 'Сочинение 11 класс',
}

export const StatsModeLabel = {
  day: 'по дням',
  week: 'по неделям',
  month: 'по месяцам',
  year: 'по годам',
} as const

export const LogTypeLabel = {
  create: 'создание',
  update: 'обновление',
  delete: 'удаление',
  view: 'просмотр',
  auth: 'авторизация',
} as const

export const LogTableLabel = {
  client_payments: 'client_payments',
  client_reviews: 'client_reviews',
  client_tests: 'client_tests',
  comments: 'comments',
  client_lessons: 'client_lessons',
  contract_version_payments: 'contract_version_payments',
  contract_version_programs: 'contract_version_programs',
  contract_versions: 'contract_versions',
  contracts: 'contracts',
  event_participants: 'event_participants',
  events: 'events',
  grades: 'grades',
  groups: 'groups',
  lessons: 'lessons',
  reports: 'reports',
  telegram_messages: 'telegram_messages',
  tests: 'tests',
  vacations: 'vacations',
} as const

export const ClientTestStatusLabel = {
  new: 'не пройден',
  active: 'активен',
  finished: 'завершен',
} as const

export const CallAppStatusFilterLabel = {
  all: 'все звонки',
  missed: 'пропущенные',
  active: 'активные',
  outgoing: 'исходящие',
} as const

export const SwampFilterStatusLabel = {
  toFulfil: 'к исполнению',
  exceedNoGroup: 'избыток по услугам + не в группе',
  completeNoGroup: 'исполнено + не в группе',
  inProcess: 'исполняется',
  exceedInGroup: 'избыток по услугам + в группе',
  completeInGroup: 'исполнено + в группе',
} as const

export const SendToLabel = {
  studentsAndParents: 'ученикам и родителям',
  students: 'только ученикам',
  parents: 'только родителям',
} as const

export const EventParticipantConfirmationLabel = {
  pending: 'не подтвердил участие',
  confirmed: 'подтвердил участие',
  rejected: 'отказался от участия',
} as const

export const TelegramListStatusLabel = {
  scheduled: 'запланировано',
  sending: 'отправляется',
  sent: 'отправлено',
} as const

export const ErrorCodeLabel = [1000] as const

export const PassTypeLabel = {
  person: 'на человека',
  car: 'на машину',
} as const

export const PassStatusLabel = {
  active: 'не использован',
  used: 'использован',
  expired: 'истёк',
} as const

export const DirectionLabel = {
  courses9: 'курсы-9',
  courses10: 'курсы-10',
  courses11: 'курсы-11',
  school8: 'школа-8',
  school9: 'школа-9',
  school10: 'школа-10',
  school11: 'школа-11',
  external: 'экстернат',
  practicum: 'практикум',
  egeTrial: 'пробный ЕГЭ',
  python: 'python',
  english: 'английский',
  online: 'онлайн',
  coursesExtra: 'курсы-доп',
} as const

export const ReportStatusLabel = {
  new: 'новый',
  toCheck: 'на проверку',
  refused: 'возвращено',
  moderated: 'промодерировано',
  published: 'опубликовано',
  empty: 'пустой отчет',
} as const
