export const ProgramLabel = {
  math1: 'математика 1 класс',
  math2: 'математика 2 класс',
  math3: 'математика 3 класс',
  math4: 'математика 4 класс',
  math5: 'математика 5 класс',
  math6: 'математика 6 класс',
  math7: 'математика 7 класс',
  math8: 'математика 8 класс',
  math9: 'математика 9 класс',
  math10: 'математика 10 класс',
  math11: 'математика 11 класс',
  mathStudents: 'математика студенты',
  mathOther: 'математика остальные',
  mathExternal: 'математика экстернат',
  mathSchool8: 'математика 8 класс – школа',
  mathSchool9: 'математика 9 класс – школа',
  mathSchool10: 'математика 10 класс – школа',
  mathSchool11: 'математика 11 класс - школа',
  mathPract11: 'математика 11 класс – практикум',
  phys1: 'физика 1 класс',
  phys2: 'физика 2 класс',
  phys3: 'физика 3 класс',
  phys4: 'физика 4 класс',
  phys5: 'физика 5 класс',
  phys6: 'физика 6 класс',
  phys7: 'физика 7 класс',
  phys8: 'физика 8 класс',
  phys9: 'физика 9 класс',
  phys10: 'физика 10 класс',
  phys11: 'физика 11 класс',
  physStudents: 'физика студенты',
  physOther: 'физика остальные',
  physExternal: 'физика экстернат',
  physSchool8: 'физика 8 класс – школа',
  physSchool9: 'физика 9 класс – школа',
  physSchool10: 'физика 10 класс – школа',
  physSchool11: 'физика 11 класс - школа',
  physPract11: 'физика 11 класс – практикум',
  chem1: 'химия 1 класс',
  chem2: 'химия 2 класс',
  chem3: 'химия 3 класс',
  chem4: 'химия 4 класс',
  chem5: 'химия 5 класс',
  chem6: 'химия 6 класс',
  chem7: 'химия 7 класс',
  chem8: 'химия 8 класс',
  chem9: 'химия 9 класс',
  chem10: 'химия 10 класс',
  chem11: 'химия 11 класс',
  chemStudents: 'химия студенты',
  chemOther: 'химия остальные',
  chemExternal: 'химия экстернат',
  chemSchool8: 'химия 8 класс – школа',
  chemSchool9: 'химия 9 класс – школа',
  chemSchool10: 'химия 10 класс – школа',
  chemSchool11: 'химия 11 класс - школа',
  chemPract11: 'химия 11 класс – практикум',
  bio1: 'биология 1 класс',
  bio2: 'биология 2 класс',
  bio3: 'биология 3 класс',
  bio4: 'биология 4 класс',
  bio5: 'биология 5 класс',
  bio6: 'биология 6 класс',
  bio7: 'биология 7 класс',
  bio8: 'биология 8 класс',
  bio9: 'биология 9 класс',
  bio10: 'биология 10 класс',
  bio11: 'биология 11 класс',
  bioStudents: 'биология студенты',
  bioOther: 'биология остальные',
  bioExternal: 'биология экстернат',
  bioSchool8: 'биология 8 класс – школа',
  bioSchool9: 'биология 9 класс – школа',
  bioSchool10: 'биология 10 класс – школа',
  bioSchool11: 'биология 11 класс - школа',
  bioPract11: 'биология 11 класс – практикум',
  inf1: 'информатика 1 класс',
  inf2: 'информатика 2 класс',
  inf3: 'информатика 3 класс',
  inf4: 'информатика 4 класс',
  inf5: 'информатика 5 класс',
  inf6: 'информатика 6 класс',
  inf7: 'информатика 7 класс',
  inf8: 'информатика 8 класс',
  inf9: 'информатика 9 класс',
  inf10: 'информатика 10 класс',
  inf11: 'информатика 11 класс',
  infStudents: 'информатика студенты',
  infOther: 'информатика остальные',
  infExternal: 'информатика экстернат',
  infSchool8: 'информатика 8 класс – школа',
  infSchool9: 'информатика 9 класс – школа',
  infSchool10: 'информатика 10 класс – школа',
  infSchool11: 'информатика 11 класс - школа',
  infPract11: 'информатика 11 класс – практикум',
  rus1: 'русский язык 1 класс',
  rus2: 'русский язык 2 класс',
  rus3: 'русский язык 3 класс',
  rus4: 'русский язык 4 класс',
  rus5: 'русский язык 5 класс',
  rus6: 'русский язык 6 класс',
  rus7: 'русский язык 7 класс',
  rus8: 'русский язык 8 класс',
  rus9: 'русский язык 9 класс',
  rus10: 'русский язык 10 класс',
  rus11: 'русский язык 11 класс',
  rusStudents: 'русский язык студенты',
  rusOther: 'русский язык остальные',
  rusExternal: 'русский язык экстернат',
  rusSchool8: 'русский язык 8 класс – школа',
  rusSchool9: 'русский язык 9 класс – школа',
  rusSchool10: 'русский язык 10 класс – школа',
  rusSchool11: 'русский язык 11 класс - школа',
  rusPract11: 'русский язык 11 класс – практикум',
  lit1: 'литература 1 класс',
  lit2: 'литература 2 класс',
  lit3: 'литература 3 класс',
  lit4: 'литература 4 класс',
  lit5: 'литература 5 класс',
  lit6: 'литература 6 класс',
  lit7: 'литература 7 класс',
  lit8: 'литература 8 класс',
  lit9: 'литература 9 класс',
  lit10: 'литература 10 класс',
  lit11: 'литература 11 класс',
  litStudents: 'литература студенты',
  litOther: 'литература остальные',
  litExternal: 'литература экстернат',
  litSchool8: 'литература 8 класс – школа',
  litSchool9: 'литература 9 класс – школа',
  litSchool10: 'литература 10 класс – школа',
  litSchool11: 'литература 11 класс - школа',
  litPract11: 'литература 11 класс – практикум',
  soc1: 'обществознание 1 класс',
  soc2: 'обществознание 2 класс',
  soc3: 'обществознание 3 класс',
  soc4: 'обществознание 4 класс',
  soc5: 'обществознание 5 класс',
  soc6: 'обществознание 6 класс',
  soc7: 'обществознание 7 класс',
  soc8: 'обществознание 8 класс',
  soc9: 'обществознание 9 класс',
  soc10: 'обществознание 10 класс',
  soc11: 'обществознание 11 класс',
  socStudents: 'обществознание студенты',
  socOther: 'обществознание остальные',
  socExternal: 'обществознание экстернат',
  socSchool8: 'обществознание 8 класс – школа',
  socSchool9: 'обществознание 9 класс – школа',
  socSchool10: 'обществознание 10 класс – школа',
  socSchool11: 'обществознание 11 класс - школа',
  socPract11: 'обществознание 11 класс – практикум',
  his1: 'история 1 класс',
  his2: 'история 2 класс',
  his3: 'история 3 класс',
  his4: 'история 4 класс',
  his5: 'история 5 класс',
  his6: 'история 6 класс',
  his7: 'история 7 класс',
  his8: 'история 8 класс',
  his9: 'история 9 класс',
  his10: 'история 10 класс',
  his11: 'история 11 класс',
  hisStudents: 'история студенты',
  hisOther: 'история остальные',
  hisExternal: 'история экстернат',
  hisSchool8: 'история 8 класс – школа',
  hisSchool9: 'история 9 класс – школа',
  hisSchool10: 'история 10 класс – школа',
  hisSchool11: 'история 11 класс - школа',
  hisPract11: 'история 11 класс – практикум',
  eng1: 'английский язык 1 класс',
  eng2: 'английский язык 2 класс',
  eng3: 'английский язык 3 класс',
  eng4: 'английский язык 4 класс',
  eng5: 'английский язык 5 класс',
  eng6: 'английский язык 6 класс',
  eng7: 'английский язык 7 класс',
  eng8: 'английский язык 8 класс',
  eng9: 'английский язык 9 класс',
  eng10: 'английский язык 10 класс',
  eng11: 'английский язык 11 класс',
  engStudents: 'английский язык студенты',
  engOther: 'английский язык остальные',
  engExternal: 'английский язык экстернат',
  engSchool8: 'английский язык 8 класс – школа',
  engSchool9: 'английский язык 9 класс – школа',
  engSchool10: 'английский язык 10 класс – школа',
  engSchool11: 'английский язык 11 класс - школа',
  engPract11: 'английский язык 11 класс – практикум',
  geo1: 'география 1 класс',
  geo2: 'география 2 класс',
  geo3: 'география 3 класс',
  geo4: 'география 4 класс',
  geo5: 'география 5 класс',
  geo6: 'география 6 класс',
  geo7: 'география 7 класс',
  geo8: 'география 8 класс',
  geo9: 'география 9 класс',
  geo10: 'география 10 класс',
  geo11: 'география 11 класс',
  geoStudents: 'география студенты',
  geoOther: 'география остальные',
  geoExternal: 'география экстернат',
  geoSchool8: 'география 8 класс – школа',
  geoSchool9: 'география 9 класс – школа',
  geoSchool10: 'география 10 класс – школа',
  geoSchool11: 'география 11 класс - школа',
  geoPract11: 'география 11 класс – практикум',
  soch1: 'сочинение 1 класс',
  soch2: 'сочинение 2 класс',
  soch3: 'сочинение 3 класс',
  soch4: 'сочинение 4 класс',
  soch5: 'сочинение 5 класс',
  soch6: 'сочинение 6 класс',
  soch7: 'сочинение 7 класс',
  soch8: 'сочинение 8 класс',
  soch9: 'сочинение 9 класс',
  soch10: 'сочинение 10 класс',
  soch11: 'сочинение 11 класс',
  sochStudents: 'сочинение студенты',
  sochOther: 'сочинение остальные',
  sochExternal: 'сочинение экстернат',
  sochSchool8: 'сочинение 8 класс – школа',
  sochSchool9: 'сочинение 9 класс – школа',
  sochSchool10: 'сочинение 10 класс – школа',
  sochSchool11: 'сочинение 11 класс - школа',
  sochPract11: 'сочинение 11 класс – практикум',
  infOge1: 'ИНФ ОГЭ 1 класс',
  infOge2: 'ИНФ ОГЭ 2 класс',
  infOge3: 'ИНФ ОГЭ 3 класс',
  infOge4: 'ИНФ ОГЭ 4 класс',
  infOge5: 'ИНФ ОГЭ 5 класс',
  infOge6: 'ИНФ ОГЭ 6 класс',
  infOge7: 'ИНФ ОГЭ 7 класс',
  infOge8: 'ИНФ ОГЭ 8 класс',
  infOge9: 'ИНФ ОГЭ 9 класс',
  infOge10: 'ИНФ ОГЭ 10 класс',
  infOge11: 'ИНФ ОГЭ 11 класс',
  infOgeStudents: 'ИНФ ОГЭ студенты',
  infOgeOther: 'ИНФ ОГЭ остальные',
  infOgeExternal: 'ИНФ ОГЭ экстернат',
  infOgeSchool8: 'ИНФ ОГЭ 8 класс – школа',
  infOgeSchool9: 'ИНФ ОГЭ 9 класс – школа',
  infOgeSchool10: 'ИНФ ОГЭ 10 класс – школа',
  infOgeSchool11: 'ИНФ ОГЭ 11 класс - школа',
  infOgePract11: 'ИНФ ОГЭ 11 класс – практикум',
  physOge1: 'ФИЗ ОГЭ 1 класс',
  physOge2: 'ФИЗ ОГЭ 2 класс',
  physOge3: 'ФИЗ ОГЭ 3 класс',
  physOge4: 'ФИЗ ОГЭ 4 класс',
  physOge5: 'ФИЗ ОГЭ 5 класс',
  physOge6: 'ФИЗ ОГЭ 6 класс',
  physOge7: 'ФИЗ ОГЭ 7 класс',
  physOge8: 'ФИЗ ОГЭ 8 класс',
  physOge9: 'ФИЗ ОГЭ 9 класс',
  physOge10: 'ФИЗ ОГЭ 10 класс',
  physOge11: 'ФИЗ ОГЭ 11 класс',
  physOgeStudents: 'ФИЗ ОГЭ студенты',
  physOgeOther: 'ФИЗ ОГЭ остальные',
  physOgeExternal: 'ФИЗ ОГЭ экстернат',
  physOgeSchool8: 'ФИЗ ОГЭ 8 класс – школа',
  physOgeSchool9: 'ФИЗ ОГЭ 9 класс – школа',
  physOgeSchool10: 'ФИЗ ОГЭ 10 класс – школа',
  physOgeSchool11: 'ФИЗ ОГЭ 11 класс - школа',
  physOgePract11: 'ФИЗ ОГЭ 11 класс – практикум',
  chemOge1: 'ХИМ ОГЭ 1 класс',
  chemOge2: 'ХИМ ОГЭ 2 класс',
  chemOge3: 'ХИМ ОГЭ 3 класс',
  chemOge4: 'ХИМ ОГЭ 4 класс',
  chemOge5: 'ХИМ ОГЭ 5 класс',
  chemOge6: 'ХИМ ОГЭ 6 класс',
  chemOge7: 'ХИМ ОГЭ 7 класс',
  chemOge8: 'ХИМ ОГЭ 8 класс',
  chemOge9: 'ХИМ ОГЭ 9 класс',
  chemOge10: 'ХИМ ОГЭ 10 класс',
  chemOge11: 'ХИМ ОГЭ 11 класс',
  chemOgeStudents: 'ХИМ ОГЭ студенты',
  chemOgeOther: 'ХИМ ОГЭ остальные',
  chemOgeExternal: 'ХИМ ОГЭ экстернат',
  chemOgeSchool8: 'ХИМ ОГЭ 8 класс – школа',
  chemOgeSchool9: 'ХИМ ОГЭ 9 класс – школа',
  chemOgeSchool10: 'ХИМ ОГЭ 10 класс – школа',
  chemOgeSchool11: 'ХИМ ОГЭ 11 класс - школа',
  chemOgePract11: 'ХИМ ОГЭ 11 класс – практикум',
  bioOge1: 'БИО ОГЭ 1 класс',
  bioOge2: 'БИО ОГЭ 2 класс',
  bioOge3: 'БИО ОГЭ 3 класс',
  bioOge4: 'БИО ОГЭ 4 класс',
  bioOge5: 'БИО ОГЭ 5 класс',
  bioOge6: 'БИО ОГЭ 6 класс',
  bioOge7: 'БИО ОГЭ 7 класс',
  bioOge8: 'БИО ОГЭ 8 класс',
  bioOge9: 'БИО ОГЭ 9 класс',
  bioOge10: 'БИО ОГЭ 10 класс',
  bioOge11: 'БИО ОГЭ 11 класс',
  bioOgeStudents: 'БИО ОГЭ студенты',
  bioOgeOther: 'БИО ОГЭ остальные',
  bioOgeExternal: 'БИО ОГЭ экстернат',
  bioOgeSchool8: 'БИО ОГЭ 8 класс – школа',
  bioOgeSchool9: 'БИО ОГЭ 9 класс – школа',
  bioOgeSchool10: 'БИО ОГЭ 10 класс – школа',
  bioOgeSchool11: 'БИО ОГЭ 11 класс - школа',
  bioOgePract11: 'БИО ОГЭ 11 класс – практикум',
  litOge1: 'ЛИТ ОГЭ 1 класс',
  litOge2: 'ЛИТ ОГЭ 2 класс',
  litOge3: 'ЛИТ ОГЭ 3 класс',
  litOge4: 'ЛИТ ОГЭ 4 класс',
  litOge5: 'ЛИТ ОГЭ 5 класс',
  litOge6: 'ЛИТ ОГЭ 6 класс',
  litOge7: 'ЛИТ ОГЭ 7 класс',
  litOge8: 'ЛИТ ОГЭ 8 класс',
  litOge9: 'ЛИТ ОГЭ 9 класс',
  litOge10: 'ЛИТ ОГЭ 10 класс',
  litOge11: 'ЛИТ ОГЭ 11 класс',
  litOgeStudents: 'ЛИТ ОГЭ студенты',
  litOgeOther: 'ЛИТ ОГЭ остальные',
  litOgeExternal: 'ЛИТ ОГЭ экстернат',
  litOgeSchool8: 'ЛИТ ОГЭ 8 класс – школа',
  litOgeSchool9: 'ЛИТ ОГЭ 9 класс – школа',
  litOgeSchool10: 'ЛИТ ОГЭ 10 класс – школа',
  litOgeSchool11: 'ЛИТ ОГЭ 11 класс - школа',
  litOgePract11: 'ЛИТ ОГЭ 11 класс – практикум',
  engOge1: 'АНГ ОГЭ 1 класс',
  engOge2: 'АНГ ОГЭ 2 класс',
  engOge3: 'АНГ ОГЭ 3 класс',
  engOge4: 'АНГ ОГЭ 4 класс',
  engOge5: 'АНГ ОГЭ 5 класс',
  engOge6: 'АНГ ОГЭ 6 класс',
  engOge7: 'АНГ ОГЭ 7 класс',
  engOge8: 'АНГ ОГЭ 8 класс',
  engOge9: 'АНГ ОГЭ 9 класс',
  engOge10: 'АНГ ОГЭ 10 класс',
  engOge11: 'АНГ ОГЭ 11 класс',
  engOgeStudents: 'АНГ ОГЭ студенты',
  engOgeOther: 'АНГ ОГЭ остальные',
  engOgeExternal: 'АНГ ОГЭ экстернат',
  engOgeSchool8: 'АНГ ОГЭ 8 класс – школа',
  engOgeSchool9: 'АНГ ОГЭ 9 класс – школа',
  engOgeSchool10: 'АНГ ОГЭ 10 класс – школа',
  engOgeSchool11: 'АНГ ОГЭ 11 класс - школа',
  engOgePract11: 'АНГ ОГЭ 11 класс – практикум',
  socOge1: 'ОБЩ ОГЭ 1 класс',
  socOge2: 'ОБЩ ОГЭ 2 класс',
  socOge3: 'ОБЩ ОГЭ 3 класс',
  socOge4: 'ОБЩ ОГЭ 4 класс',
  socOge5: 'ОБЩ ОГЭ 5 класс',
  socOge6: 'ОБЩ ОГЭ 6 класс',
  socOge7: 'ОБЩ ОГЭ 7 класс',
  socOge8: 'ОБЩ ОГЭ 8 класс',
  socOge9: 'ОБЩ ОГЭ 9 класс',
  socOge10: 'ОБЩ ОГЭ 10 класс',
  socOge11: 'ОБЩ ОГЭ 11 класс',
  socOgeStudents: 'ОБЩ ОГЭ студенты',
  socOgeOther: 'ОБЩ ОГЭ остальные',
  socOgeExternal: 'ОБЩ ОГЭ экстернат',
  socOgeSchool8: 'ОБЩ ОГЭ 8 класс – школа',
  socOgeSchool9: 'ОБЩ ОГЭ 9 класс – школа',
  socOgeSchool10: 'ОБЩ ОГЭ 10 класс – школа',
  socOgeSchool11: 'ОБЩ ОГЭ 11 класс - школа',
  socOgePract11: 'ОБЩ ОГЭ 11 класс – практикум',
  hisOge1: 'ИСТ ОГЭ 1 класс',
  hisOge2: 'ИСТ ОГЭ 2 класс',
  hisOge3: 'ИСТ ОГЭ 3 класс',
  hisOge4: 'ИСТ ОГЭ 4 класс',
  hisOge5: 'ИСТ ОГЭ 5 класс',
  hisOge6: 'ИСТ ОГЭ 6 класс',
  hisOge7: 'ИСТ ОГЭ 7 класс',
  hisOge8: 'ИСТ ОГЭ 8 класс',
  hisOge9: 'ИСТ ОГЭ 9 класс',
  hisOge10: 'ИСТ ОГЭ 10 класс',
  hisOge11: 'ИСТ ОГЭ 11 класс',
  hisOgeStudents: 'ИСТ ОГЭ студенты',
  hisOgeOther: 'ИСТ ОГЭ остальные',
  hisOgeExternal: 'ИСТ ОГЭ экстернат',
  hisOgeSchool8: 'ИСТ ОГЭ 8 класс – школа',
  hisOgeSchool9: 'ИСТ ОГЭ 9 класс – школа',
  hisOgeSchool10: 'ИСТ ОГЭ 10 класс – школа',
  hisOgeSchool11: 'ИСТ ОГЭ 11 класс - школа',
  hisOgePract11: 'ИСТ ОГЭ 11 класс – практикум',
  mathProf1: 'МАТ ПРОФ 1 класс',
  mathProf2: 'МАТ ПРОФ 2 класс',
  mathProf3: 'МАТ ПРОФ 3 класс',
  mathProf4: 'МАТ ПРОФ 4 класс',
  mathProf5: 'МАТ ПРОФ 5 класс',
  mathProf6: 'МАТ ПРОФ 6 класс',
  mathProf7: 'МАТ ПРОФ 7 класс',
  mathProf8: 'МАТ ПРОФ 8 класс',
  mathProf9: 'МАТ ПРОФ 9 класс',
  mathProf10: 'МАТ ПРОФ 10 класс',
  mathProf11: 'МАТ ПРОФ 11 класс',
  mathProfStudents: 'МАТ ПРОФ студенты',
  mathProfOther: 'МАТ ПРОФ остальные',
  mathProfExternal: 'МАТ ПРОФ экстернат',
  mathProfSchool8: 'МАТ ПРОФ 8 класс – школа',
  mathProfSchool9: 'МАТ ПРОФ 9 класс – школа',
  mathProfSchool10: 'МАТ ПРОФ 10 класс – школа',
  mathProfSchool11: 'МАТ ПРОФ 11 класс - школа',
  mathProfPract11: 'МАТ ПРОФ 11 класс – практикум',
  mathBase1: 'МАТ БАЗА 1 класс',
  mathBase2: 'МАТ БАЗА 2 класс',
  mathBase3: 'МАТ БАЗА 3 класс',
  mathBase4: 'МАТ БАЗА 4 класс',
  mathBase5: 'МАТ БАЗА 5 класс',
  mathBase6: 'МАТ БАЗА 6 класс',
  mathBase7: 'МАТ БАЗА 7 класс',
  mathBase8: 'МАТ БАЗА 8 класс',
  mathBase9: 'МАТ БАЗА 9 класс',
  mathBase10: 'МАТ БАЗА 10 класс',
  mathBase11: 'МАТ БАЗА 11 класс',
  mathBaseStudents: 'МАТ БАЗА студенты',
  mathBaseOther: 'МАТ БАЗА остальные',
  mathBaseExternal: 'МАТ БАЗА экстернат',
  mathBaseSchool8: 'МАТ БАЗА 8 класс – школа',
  mathBaseSchool9: 'МАТ БАЗА 9 класс – школа',
  mathBaseSchool10: 'МАТ БАЗА 10 класс – школа',
  mathBaseSchool11: 'МАТ БАЗА 11 класс - школа',
  mathBasePract11: 'МАТ БАЗА 11 класс – практикум',
  mathOnline1: 'ОНЛАЙН МАТ 1 класс',
  mathOnline2: 'ОНЛАЙН МАТ 2 класс',
  mathOnline3: 'ОНЛАЙН МАТ 3 класс',
  mathOnline4: 'ОНЛАЙН МАТ 4 класс',
  mathOnline5: 'ОНЛАЙН МАТ 5 класс',
  mathOnline6: 'ОНЛАЙН МАТ 6 класс',
  mathOnline7: 'ОНЛАЙН МАТ 7 класс',
  mathOnline8: 'ОНЛАЙН МАТ 8 класс',
  mathOnline9: 'ОНЛАЙН МАТ 9 класс',
  mathOnline10: 'ОНЛАЙН МАТ 10 класс',
  mathOnline11: 'ОНЛАЙН МАТ 11 класс',
  mathOnlineStudents: 'ОНЛАЙН МАТ студенты',
  mathOnlineOther: 'ОНЛАЙН МАТ остальные',
  mathOnlineExternal: 'ОНЛАЙН МАТ экстернат',
  mathOnlineSchool8: 'ОНЛАЙН МАТ 8 класс – школа',
  mathOnlineSchool9: 'ОНЛАЙН МАТ 9 класс – школа',
  mathOnlineSchool10: 'ОНЛАЙН МАТ 10 класс – школа',
  mathOnlineSchool11: 'ОНЛАЙН МАТ 11 класс - школа',
  mathOnlinePract11: 'ОНЛАЙН МАТ 11 класс – практикум',
  rusOnline1: 'ОНЛАЙН РУС 1 класс',
  rusOnline2: 'ОНЛАЙН РУС 2 класс',
  rusOnline3: 'ОНЛАЙН РУС 3 класс',
  rusOnline4: 'ОНЛАЙН РУС 4 класс',
  rusOnline5: 'ОНЛАЙН РУС 5 класс',
  rusOnline6: 'ОНЛАЙН РУС 6 класс',
  rusOnline7: 'ОНЛАЙН РУС 7 класс',
  rusOnline8: 'ОНЛАЙН РУС 8 класс',
  rusOnline9: 'ОНЛАЙН РУС 9 класс',
  rusOnline10: 'ОНЛАЙН РУС 10 класс',
  rusOnline11: 'ОНЛАЙН РУС 11 класс',
  rusOnlineStudents: 'ОНЛАЙН РУС студенты',
  rusOnlineOther: 'ОНЛАЙН РУС остальные',
  rusOnlineExternal: 'ОНЛАЙН РУС экстернат',
  rusOnlineSchool8: 'ОНЛАЙН РУС 8 класс – школа',
  rusOnlineSchool9: 'ОНЛАЙН РУС 9 класс – школа',
  rusOnlineSchool10: 'ОНЛАЙН РУС 10 класс – школа',
  rusOnlineSchool11: 'ОНЛАЙН РУС 11 класс - школа',
  rusOnlinePract11: 'ОНЛАЙН РУС 11 класс – практикум',
  socOnline1: 'ОНЛАЙН ОБЩ 1 класс',
  socOnline2: 'ОНЛАЙН ОБЩ 2 класс',
  socOnline3: 'ОНЛАЙН ОБЩ 3 класс',
  socOnline4: 'ОНЛАЙН ОБЩ 4 класс',
  socOnline5: 'ОНЛАЙН ОБЩ 5 класс',
  socOnline6: 'ОНЛАЙН ОБЩ 6 класс',
  socOnline7: 'ОНЛАЙН ОБЩ 7 класс',
  socOnline8: 'ОНЛАЙН ОБЩ 8 класс',
  socOnline9: 'ОНЛАЙН ОБЩ 9 класс',
  socOnline10: 'ОНЛАЙН ОБЩ 10 класс',
  socOnline11: 'ОНЛАЙН ОБЩ 11 класс',
  socOnlineStudents: 'ОНЛАЙН ОБЩ студенты',
  socOnlineOther: 'ОНЛАЙН ОБЩ остальные',
  socOnlineExternal: 'ОНЛАЙН ОБЩ экстернат',
  socOnlineSchool8: 'ОНЛАЙН ОБЩ 8 класс – школа',
  socOnlineSchool9: 'ОНЛАЙН ОБЩ 9 класс – школа',
  socOnlineSchool10: 'ОНЛАЙН ОБЩ 10 класс – школа',
  socOnlineSchool11: 'ОНЛАЙН ОБЩ 11 класс - школа',
  socOnlinePract11: 'ОНЛАЙН ОБЩ 11 класс – практикум',
  mathPracticum1: 'МАТ ПРАКТИКУМ 1 класс',
  mathPracticum2: 'МАТ ПРАКТИКУМ 2 класс',
  mathPracticum3: 'МАТ ПРАКТИКУМ 3 класс',
  mathPracticum4: 'МАТ ПРАКТИКУМ 4 класс',
  mathPracticum5: 'МАТ ПРАКТИКУМ 5 класс',
  mathPracticum6: 'МАТ ПРАКТИКУМ 6 класс',
  mathPracticum7: 'МАТ ПРАКТИКУМ 7 класс',
  mathPracticum8: 'МАТ ПРАКТИКУМ 8 класс',
  mathPracticum9: 'МАТ ПРАКТИКУМ 9 класс',
  mathPracticum10: 'МАТ ПРАКТИКУМ 10 класс',
  mathPracticum11: 'МАТ ПРАКТИКУМ 11 класс',
  mathPracticumStudents: 'МАТ ПРАКТИКУМ студенты',
  mathPracticumOther: 'МАТ ПРАКТИКУМ остальные',
  mathPracticumExternal: 'МАТ ПРАКТИКУМ экстернат',
  mathPracticumSchool8: 'МАТ ПРАКТИКУМ 8 класс – школа',
  mathPracticumSchool9: 'МАТ ПРАКТИКУМ 9 класс – школа',
  mathPracticumSchool10: 'МАТ ПРАКТИКУМ 10 класс – школа',
  mathPracticumSchool11: 'МАТ ПРАКТИКУМ 11 класс - школа',
  mathPracticumPract11: 'МАТ ПРАКТИКУМ 11 класс – практикум',
  socPracticum1: 'ОБЩ ПРАКТИКУМ 1 класс',
  socPracticum2: 'ОБЩ ПРАКТИКУМ 2 класс',
  socPracticum3: 'ОБЩ ПРАКТИКУМ 3 класс',
  socPracticum4: 'ОБЩ ПРАКТИКУМ 4 класс',
  socPracticum5: 'ОБЩ ПРАКТИКУМ 5 класс',
  socPracticum6: 'ОБЩ ПРАКТИКУМ 6 класс',
  socPracticum7: 'ОБЩ ПРАКТИКУМ 7 класс',
  socPracticum8: 'ОБЩ ПРАКТИКУМ 8 класс',
  socPracticum9: 'ОБЩ ПРАКТИКУМ 9 класс',
  socPracticum10: 'ОБЩ ПРАКТИКУМ 10 класс',
  socPracticum11: 'ОБЩ ПРАКТИКУМ 11 класс',
  socPracticumStudents: 'ОБЩ ПРАКТИКУМ студенты',
  socPracticumOther: 'ОБЩ ПРАКТИКУМ остальные',
  socPracticumExternal: 'ОБЩ ПРАКТИКУМ экстернат',
  socPracticumSchool8: 'ОБЩ ПРАКТИКУМ 8 класс – школа',
  socPracticumSchool9: 'ОБЩ ПРАКТИКУМ 9 класс – школа',
  socPracticumSchool10: 'ОБЩ ПРАКТИКУМ 10 класс – школа',
  socPracticumSchool11: 'ОБЩ ПРАКТИКУМ 11 класс - школа',
  socPracticumPract11: 'ОБЩ ПРАКТИКУМ 11 класс – практикум',
  physPracticum1: 'ФИЗ ПРАКТИКУМ 1 класс',
  physPracticum2: 'ФИЗ ПРАКТИКУМ 2 класс',
  physPracticum3: 'ФИЗ ПРАКТИКУМ 3 класс',
  physPracticum4: 'ФИЗ ПРАКТИКУМ 4 класс',
  physPracticum5: 'ФИЗ ПРАКТИКУМ 5 класс',
  physPracticum6: 'ФИЗ ПРАКТИКУМ 6 класс',
  physPracticum7: 'ФИЗ ПРАКТИКУМ 7 класс',
  physPracticum8: 'ФИЗ ПРАКТИКУМ 8 класс',
  physPracticum9: 'ФИЗ ПРАКТИКУМ 9 класс',
  physPracticum10: 'ФИЗ ПРАКТИКУМ 10 класс',
  physPracticum11: 'ФИЗ ПРАКТИКУМ 11 класс',
  physPracticumStudents: 'ФИЗ ПРАКТИКУМ студенты',
  physPracticumOther: 'ФИЗ ПРАКТИКУМ остальные',
  physPracticumExternal: 'ФИЗ ПРАКТИКУМ экстернат',
  physPracticumSchool8: 'ФИЗ ПРАКТИКУМ 8 класс – школа',
  physPracticumSchool9: 'ФИЗ ПРАКТИКУМ 9 класс – школа',
  physPracticumSchool10: 'ФИЗ ПРАКТИКУМ 10 класс – школа',
  physPracticumSchool11: 'ФИЗ ПРАКТИКУМ 11 класс - школа',
  physPracticumPract11: 'ФИЗ ПРАКТИКУМ 11 класс – практикум',
  chemPracticum1: 'ХИМ ПРАКТИКУМ 1 класс',
  chemPracticum2: 'ХИМ ПРАКТИКУМ 2 класс',
  chemPracticum3: 'ХИМ ПРАКТИКУМ 3 класс',
  chemPracticum4: 'ХИМ ПРАКТИКУМ 4 класс',
  chemPracticum5: 'ХИМ ПРАКТИКУМ 5 класс',
  chemPracticum6: 'ХИМ ПРАКТИКУМ 6 класс',
  chemPracticum7: 'ХИМ ПРАКТИКУМ 7 класс',
  chemPracticum8: 'ХИМ ПРАКТИКУМ 8 класс',
  chemPracticum9: 'ХИМ ПРАКТИКУМ 9 класс',
  chemPracticum10: 'ХИМ ПРАКТИКУМ 10 класс',
  chemPracticum11: 'ХИМ ПРАКТИКУМ 11 класс',
  chemPracticumStudents: 'ХИМ ПРАКТИКУМ студенты',
  chemPracticumOther: 'ХИМ ПРАКТИКУМ остальные',
  chemPracticumExternal: 'ХИМ ПРАКТИКУМ экстернат',
  chemPracticumSchool8: 'ХИМ ПРАКТИКУМ 8 класс – школа',
  chemPracticumSchool9: 'ХИМ ПРАКТИКУМ 9 класс – школа',
  chemPracticumSchool10: 'ХИМ ПРАКТИКУМ 10 класс – школа',
  chemPracticumSchool11: 'ХИМ ПРАКТИКУМ 11 класс - школа',
  chemPracticumPract11: 'ХИМ ПРАКТИКУМ 11 класс – практикум',
  bioPracticum1: 'БИО ПРАКТИКУМ 1 класс',
  bioPracticum2: 'БИО ПРАКТИКУМ 2 класс',
  bioPracticum3: 'БИО ПРАКТИКУМ 3 класс',
  bioPracticum4: 'БИО ПРАКТИКУМ 4 класс',
  bioPracticum5: 'БИО ПРАКТИКУМ 5 класс',
  bioPracticum6: 'БИО ПРАКТИКУМ 6 класс',
  bioPracticum7: 'БИО ПРАКТИКУМ 7 класс',
  bioPracticum8: 'БИО ПРАКТИКУМ 8 класс',
  bioPracticum9: 'БИО ПРАКТИКУМ 9 класс',
  bioPracticum10: 'БИО ПРАКТИКУМ 10 класс',
  bioPracticum11: 'БИО ПРАКТИКУМ 11 класс',
  bioPracticumStudents: 'БИО ПРАКТИКУМ студенты',
  bioPracticumOther: 'БИО ПРАКТИКУМ остальные',
  bioPracticumExternal: 'БИО ПРАКТИКУМ экстернат',
  bioPracticumSchool8: 'БИО ПРАКТИКУМ 8 класс – школа',
  bioPracticumSchool9: 'БИО ПРАКТИКУМ 9 класс – школа',
  bioPracticumSchool10: 'БИО ПРАКТИКУМ 10 класс – школа',
  bioPracticumSchool11: 'БИО ПРАКТИКУМ 11 класс - школа',
  bioPracticumPract11: 'БИО ПРАКТИКУМ 11 класс – практикум',
  infPracticum1: 'ИНФ ПРАКТИКУМ 1 класс',
  infPracticum2: 'ИНФ ПРАКТИКУМ 2 класс',
  infPracticum3: 'ИНФ ПРАКТИКУМ 3 класс',
  infPracticum4: 'ИНФ ПРАКТИКУМ 4 класс',
  infPracticum5: 'ИНФ ПРАКТИКУМ 5 класс',
  infPracticum6: 'ИНФ ПРАКТИКУМ 6 класс',
  infPracticum7: 'ИНФ ПРАКТИКУМ 7 класс',
  infPracticum8: 'ИНФ ПРАКТИКУМ 8 класс',
  infPracticum9: 'ИНФ ПРАКТИКУМ 9 класс',
  infPracticum10: 'ИНФ ПРАКТИКУМ 10 класс',
  infPracticum11: 'ИНФ ПРАКТИКУМ 11 класс',
  infPracticumStudents: 'ИНФ ПРАКТИКУМ студенты',
  infPracticumOther: 'ИНФ ПРАКТИКУМ остальные',
  infPracticumExternal: 'ИНФ ПРАКТИКУМ экстернат',
  infPracticumSchool8: 'ИНФ ПРАКТИКУМ 8 класс – школа',
  infPracticumSchool9: 'ИНФ ПРАКТИКУМ 9 класс – школа',
  infPracticumSchool10: 'ИНФ ПРАКТИКУМ 10 класс – школа',
  infPracticumSchool11: 'ИНФ ПРАКТИКУМ 11 класс - школа',
  infPracticumPract11: 'ИНФ ПРАКТИКУМ 11 класс – практикум',
  rusPracticum1: 'РУС ПРАКТИКУМ 1 класс',
  rusPracticum2: 'РУС ПРАКТИКУМ 2 класс',
  rusPracticum3: 'РУС ПРАКТИКУМ 3 класс',
  rusPracticum4: 'РУС ПРАКТИКУМ 4 класс',
  rusPracticum5: 'РУС ПРАКТИКУМ 5 класс',
  rusPracticum6: 'РУС ПРАКТИКУМ 6 класс',
  rusPracticum7: 'РУС ПРАКТИКУМ 7 класс',
  rusPracticum8: 'РУС ПРАКТИКУМ 8 класс',
  rusPracticum9: 'РУС ПРАКТИКУМ 9 класс',
  rusPracticum10: 'РУС ПРАКТИКУМ 10 класс',
  rusPracticum11: 'РУС ПРАКТИКУМ 11 класс',
  rusPracticumStudents: 'РУС ПРАКТИКУМ студенты',
  rusPracticumOther: 'РУС ПРАКТИКУМ остальные',
  rusPracticumExternal: 'РУС ПРАКТИКУМ экстернат',
  rusPracticumSchool8: 'РУС ПРАКТИКУМ 8 класс – школа',
  rusPracticumSchool9: 'РУС ПРАКТИКУМ 9 класс – школа',
  rusPracticumSchool10: 'РУС ПРАКТИКУМ 10 класс – школа',
  rusPracticumSchool11: 'РУС ПРАКТИКУМ 11 класс - школа',
  rusPracticumPract11: 'РУС ПРАКТИКУМ 11 класс – практикум',
  hisPracticum1: 'ИСТ ПРАКТИКУМ 1 класс',
  hisPracticum2: 'ИСТ ПРАКТИКУМ 2 класс',
  hisPracticum3: 'ИСТ ПРАКТИКУМ 3 класс',
  hisPracticum4: 'ИСТ ПРАКТИКУМ 4 класс',
  hisPracticum5: 'ИСТ ПРАКТИКУМ 5 класс',
  hisPracticum6: 'ИСТ ПРАКТИКУМ 6 класс',
  hisPracticum7: 'ИСТ ПРАКТИКУМ 7 класс',
  hisPracticum8: 'ИСТ ПРАКТИКУМ 8 класс',
  hisPracticum9: 'ИСТ ПРАКТИКУМ 9 класс',
  hisPracticum10: 'ИСТ ПРАКТИКУМ 10 класс',
  hisPracticum11: 'ИСТ ПРАКТИКУМ 11 класс',
  hisPracticumStudents: 'ИСТ ПРАКТИКУМ студенты',
  hisPracticumOther: 'ИСТ ПРАКТИКУМ остальные',
  hisPracticumExternal: 'ИСТ ПРАКТИКУМ экстернат',
  hisPracticumSchool8: 'ИСТ ПРАКТИКУМ 8 класс – школа',
  hisPracticumSchool9: 'ИСТ ПРАКТИКУМ 9 класс – школа',
  hisPracticumSchool10: 'ИСТ ПРАКТИКУМ 10 класс – школа',
  hisPracticumSchool11: 'ИСТ ПРАКТИКУМ 11 класс - школа',
  hisPracticumPract11: 'ИСТ ПРАКТИКУМ 11 класс – практикум',
  engPracticum1: 'АНГ ПРАКТИКУМ 1 класс',
  engPracticum2: 'АНГ ПРАКТИКУМ 2 класс',
  engPracticum3: 'АНГ ПРАКТИКУМ 3 класс',
  engPracticum4: 'АНГ ПРАКТИКУМ 4 класс',
  engPracticum5: 'АНГ ПРАКТИКУМ 5 класс',
  engPracticum6: 'АНГ ПРАКТИКУМ 6 класс',
  engPracticum7: 'АНГ ПРАКТИКУМ 7 класс',
  engPracticum8: 'АНГ ПРАКТИКУМ 8 класс',
  engPracticum9: 'АНГ ПРАКТИКУМ 9 класс',
  engPracticum10: 'АНГ ПРАКТИКУМ 10 класс',
  engPracticum11: 'АНГ ПРАКТИКУМ 11 класс',
  engPracticumStudents: 'АНГ ПРАКТИКУМ студенты',
  engPracticumOther: 'АНГ ПРАКТИКУМ остальные',
  engPracticumExternal: 'АНГ ПРАКТИКУМ экстернат',
  engPracticumSchool8: 'АНГ ПРАКТИКУМ 8 класс – школа',
  engPracticumSchool9: 'АНГ ПРАКТИКУМ 9 класс – школа',
  engPracticumSchool10: 'АНГ ПРАКТИКУМ 10 класс – школа',
  engPracticumSchool11: 'АНГ ПРАКТИКУМ 11 класс - школа',
  engPracticumPract11: 'АНГ ПРАКТИКУМ 11 класс – практикум',
  geoPracticum1: 'ГЕО ПРАКТИКУМ 1 класс',
  geoPracticum2: 'ГЕО ПРАКТИКУМ 2 класс',
  geoPracticum3: 'ГЕО ПРАКТИКУМ 3 класс',
  geoPracticum4: 'ГЕО ПРАКТИКУМ 4 класс',
  geoPracticum5: 'ГЕО ПРАКТИКУМ 5 класс',
  geoPracticum6: 'ГЕО ПРАКТИКУМ 6 класс',
  geoPracticum7: 'ГЕО ПРАКТИКУМ 7 класс',
  geoPracticum8: 'ГЕО ПРАКТИКУМ 8 класс',
  geoPracticum9: 'ГЕО ПРАКТИКУМ 9 класс',
  geoPracticum10: 'ГЕО ПРАКТИКУМ 10 класс',
  geoPracticum11: 'ГЕО ПРАКТИКУМ 11 класс',
  geoPracticumStudents: 'ГЕО ПРАКТИКУМ студенты',
  geoPracticumOther: 'ГЕО ПРАКТИКУМ остальные',
  geoPracticumExternal: 'ГЕО ПРАКТИКУМ экстернат',
  geoPracticumSchool8: 'ГЕО ПРАКТИКУМ 8 класс – школа',
  geoPracticumSchool9: 'ГЕО ПРАКТИКУМ 9 класс – школа',
  geoPracticumSchool10: 'ГЕО ПРАКТИКУМ 10 класс – школа',
  geoPracticumSchool11: 'ГЕО ПРАКТИКУМ 11 класс - школа',
  geoPracticumPract11: 'ГЕО ПРАКТИКУМ 11 класс – практикум',
  izl1: 'итоговое собеседование 1 класс',
  izl2: 'итоговое собеседование 2 класс',
  izl3: 'итоговое собеседование 3 класс',
  izl4: 'итоговое собеседование 4 класс',
  izl5: 'итоговое собеседование 5 класс',
  izl6: 'итоговое собеседование 6 класс',
  izl7: 'итоговое собеседование 7 класс',
  izl8: 'итоговое собеседование 8 класс',
  izl9: 'итоговое собеседование 9 класс',
  izl10: 'итоговое собеседование 10 класс',
  izl11: 'итоговое собеседование 11 класс',
  izlStudents: 'итоговое собеседование студенты',
  izlOther: 'итоговое собеседование остальные',
  izlExternal: 'итоговое собеседование экстернат',
  izlSchool8: 'итоговое собеседование 8 класс – школа',
  izlSchool9: 'итоговое собеседование 9 класс – школа',
  izlSchool10: 'итоговое собеседование 10 класс – школа',
  izlSchool11: 'итоговое собеседование 11 класс - школа',
  izlPract11: 'итоговое собеседование 11 класс – практикум',
  geoOge1: 'ГЕО ОГЭ 1 класс',
  geoOge2: 'ГЕО ОГЭ 2 класс',
  geoOge3: 'ГЕО ОГЭ 3 класс',
  geoOge4: 'ГЕО ОГЭ 4 класс',
  geoOge5: 'ГЕО ОГЭ 5 класс',
  geoOge6: 'ГЕО ОГЭ 6 класс',
  geoOge7: 'ГЕО ОГЭ 7 класс',
  geoOge8: 'ГЕО ОГЭ 8 класс',
  geoOge9: 'ГЕО ОГЭ 9 класс',
  geoOge10: 'ГЕО ОГЭ 10 класс',
  geoOge11: 'ГЕО ОГЭ 11 класс',
  geoOgeStudents: 'ГЕО ОГЭ студенты',
  geoOgeOther: 'ГЕО ОГЭ остальные',
  geoOgeExternal: 'ГЕО ОГЭ экстернат',
  geoOgeSchool8: 'ГЕО ОГЭ 8 класс – школа',
  geoOgeSchool9: 'ГЕО ОГЭ 9 класс – школа',
  geoOgeSchool10: 'ГЕО ОГЭ 10 класс – школа',
  geoOgeSchool11: 'ГЕО ОГЭ 11 класс - школа',
  geoOgePract11: 'ГЕО ОГЭ 11 класс – практикум',
  engSpoken1: 'разговорный английский 1 класс',
  engSpoken2: 'разговорный английский 2 класс',
  engSpoken3: 'разговорный английский 3 класс',
  engSpoken4: 'разговорный английский 4 класс',
  engSpoken5: 'разговорный английский 5 класс',
  engSpoken6: 'разговорный английский 6 класс',
  engSpoken7: 'разговорный английский 7 класс',
  engSpoken8: 'разговорный английский 8 класс',
  engSpoken9: 'разговорный английский 9 класс',
  engSpoken10: 'разговорный английский 10 класс',
  engSpoken11: 'разговорный английский 11 класс',
  engSpokenStudents: 'разговорный английский студенты',
  engSpokenOther: 'разговорный английский остальные',
  engSpokenExternal: 'разговорный английский экстернат',
  engSpokenSchool8: 'разговорный английский 8 класс – школа',
  engSpokenSchool9: 'разговорный английский 9 класс – школа',
  engSpokenSchool10: 'разговорный английский 10 класс – школа',
  engSpokenSchool11: 'разговорный английский 11 класс - школа',
  engSpokenPract11: 'разговорный английский 11 класс – практикум',
} as const

export const TelegramTemplateLabel = {
  reportPublished: 'отчёт отправлен',
  reportRead: 'отчёт прочитан',
  clientLessonStatus: 'опоздал/не пришёл',
}

export const ProgramShortLabel = {
  math1: '1-МАТ',
  math2: '2-МАТ',
  math3: '3-МАТ',
  math4: '4-МАТ',
  math5: '5-МАТ',
  math6: '6-МАТ',
  math7: '7-МАТ',
  math8: '8-МАТ',
  math9: '9-МАТ',
  math10: '10-МАТ',
  math11: '11-МАТ',
  mathStudents: 'C-МАТ',
  mathOther: 'O-МАТ',
  mathExternal: 'Э-МАТ',
  mathSchool8: '8Ш-МАТ',
  mathSchool9: '9Ш-МАТ',
  mathSchool10: '10Ш-МАТ',
  mathSchool11: '11Ш-МАТ',
  mathPract11: '11П-МАТ',
  phys1: '1-ФИЗ',
  phys2: '2-ФИЗ',
  phys3: '3-ФИЗ',
  phys4: '4-ФИЗ',
  phys5: '5-ФИЗ',
  phys6: '6-ФИЗ',
  phys7: '7-ФИЗ',
  phys8: '8-ФИЗ',
  phys9: '9-ФИЗ',
  phys10: '10-ФИЗ',
  phys11: '11-ФИЗ',
  physStudents: 'C-ФИЗ',
  physOther: 'O-ФИЗ',
  physExternal: 'Э-ФИЗ',
  physSchool8: '8Ш-ФИЗ',
  physSchool9: '9Ш-ФИЗ',
  physSchool10: '10Ш-ФИЗ',
  physSchool11: '11Ш-ФИЗ',
  physPract11: '11П-ФИЗ',
  chem1: '1-ХИМ',
  chem2: '2-ХИМ',
  chem3: '3-ХИМ',
  chem4: '4-ХИМ',
  chem5: '5-ХИМ',
  chem6: '6-ХИМ',
  chem7: '7-ХИМ',
  chem8: '8-ХИМ',
  chem9: '9-ХИМ',
  chem10: '10-ХИМ',
  chem11: '11-ХИМ',
  chemStudents: 'C-ХИМ',
  chemOther: 'O-ХИМ',
  chemExternal: 'Э-ХИМ',
  chemSchool8: '8Ш-ХИМ',
  chemSchool9: '9Ш-ХИМ',
  chemSchool10: '10Ш-ХИМ',
  chemSchool11: '11Ш-ХИМ',
  chemPract11: '11П-ХИМ',
  bio1: '1-БИО',
  bio2: '2-БИО',
  bio3: '3-БИО',
  bio4: '4-БИО',
  bio5: '5-БИО',
  bio6: '6-БИО',
  bio7: '7-БИО',
  bio8: '8-БИО',
  bio9: '9-БИО',
  bio10: '10-БИО',
  bio11: '11-БИО',
  bioStudents: 'C-БИО',
  bioOther: 'O-БИО',
  bioExternal: 'Э-БИО',
  bioSchool8: '8Ш-БИО',
  bioSchool9: '9Ш-БИО',
  bioSchool10: '10Ш-БИО',
  bioSchool11: '11Ш-БИО',
  bioPract11: '11П-БИО',
  inf1: '1-ИНФ',
  inf2: '2-ИНФ',
  inf3: '3-ИНФ',
  inf4: '4-ИНФ',
  inf5: '5-ИНФ',
  inf6: '6-ИНФ',
  inf7: '7-ИНФ',
  inf8: '8-ИНФ',
  inf9: '9-ИНФ',
  inf10: '10-ИНФ',
  inf11: '11-ИНФ',
  infStudents: 'C-ИНФ',
  infOther: 'O-ИНФ',
  infExternal: 'Э-ИНФ',
  infSchool8: '8Ш-ИНФ',
  infSchool9: '9Ш-ИНФ',
  infSchool10: '10Ш-ИНФ',
  infSchool11: '11Ш-ИНФ',
  infPract11: '11П-ИНФ',
  rus1: '1-РУС',
  rus2: '2-РУС',
  rus3: '3-РУС',
  rus4: '4-РУС',
  rus5: '5-РУС',
  rus6: '6-РУС',
  rus7: '7-РУС',
  rus8: '8-РУС',
  rus9: '9-РУС',
  rus10: '10-РУС',
  rus11: '11-РУС',
  rusStudents: 'C-РУС',
  rusOther: 'O-РУС',
  rusExternal: 'Э-РУС',
  rusSchool8: '8Ш-РУС',
  rusSchool9: '9Ш-РУС',
  rusSchool10: '10Ш-РУС',
  rusSchool11: '11Ш-РУС',
  rusPract11: '11П-РУС',
  lit1: '1-ЛИТ',
  lit2: '2-ЛИТ',
  lit3: '3-ЛИТ',
  lit4: '4-ЛИТ',
  lit5: '5-ЛИТ',
  lit6: '6-ЛИТ',
  lit7: '7-ЛИТ',
  lit8: '8-ЛИТ',
  lit9: '9-ЛИТ',
  lit10: '10-ЛИТ',
  lit11: '11-ЛИТ',
  litStudents: 'C-ЛИТ',
  litOther: 'O-ЛИТ',
  litExternal: 'Э-ЛИТ',
  litSchool8: '8Ш-ЛИТ',
  litSchool9: '9Ш-ЛИТ',
  litSchool10: '10Ш-ЛИТ',
  litSchool11: '11Ш-ЛИТ',
  litPract11: '11П-ЛИТ',
  soc1: '1-ОБЩ',
  soc2: '2-ОБЩ',
  soc3: '3-ОБЩ',
  soc4: '4-ОБЩ',
  soc5: '5-ОБЩ',
  soc6: '6-ОБЩ',
  soc7: '7-ОБЩ',
  soc8: '8-ОБЩ',
  soc9: '9-ОБЩ',
  soc10: '10-ОБЩ',
  soc11: '11-ОБЩ',
  socStudents: 'C-ОБЩ',
  socOther: 'O-ОБЩ',
  socExternal: 'Э-ОБЩ',
  socSchool8: '8Ш-ОБЩ',
  socSchool9: '9Ш-ОБЩ',
  socSchool10: '10Ш-ОБЩ',
  socSchool11: '11Ш-ОБЩ',
  socPract11: '11П-ОБЩ',
  his1: '1-ИСТ',
  his2: '2-ИСТ',
  his3: '3-ИСТ',
  his4: '4-ИСТ',
  his5: '5-ИСТ',
  his6: '6-ИСТ',
  his7: '7-ИСТ',
  his8: '8-ИСТ',
  his9: '9-ИСТ',
  his10: '10-ИСТ',
  his11: '11-ИСТ',
  hisStudents: 'C-ИСТ',
  hisOther: 'O-ИСТ',
  hisExternal: 'Э-ИСТ',
  hisSchool8: '8Ш-ИСТ',
  hisSchool9: '9Ш-ИСТ',
  hisSchool10: '10Ш-ИСТ',
  hisSchool11: '11Ш-ИСТ',
  hisPract11: '11П-ИСТ',
  eng1: '1-АНГ',
  eng2: '2-АНГ',
  eng3: '3-АНГ',
  eng4: '4-АНГ',
  eng5: '5-АНГ',
  eng6: '6-АНГ',
  eng7: '7-АНГ',
  eng8: '8-АНГ',
  eng9: '9-АНГ',
  eng10: '10-АНГ',
  eng11: '11-АНГ',
  engStudents: 'C-АНГ',
  engOther: 'O-АНГ',
  engExternal: 'Э-АНГ',
  engSchool8: '8Ш-АНГ',
  engSchool9: '9Ш-АНГ',
  engSchool10: '10Ш-АНГ',
  engSchool11: '11Ш-АНГ',
  engPract11: '11П-АНГ',
  geo1: '1-ГЕО',
  geo2: '2-ГЕО',
  geo3: '3-ГЕО',
  geo4: '4-ГЕО',
  geo5: '5-ГЕО',
  geo6: '6-ГЕО',
  geo7: '7-ГЕО',
  geo8: '8-ГЕО',
  geo9: '9-ГЕО',
  geo10: '10-ГЕО',
  geo11: '11-ГЕО',
  geoStudents: 'C-ГЕО',
  geoOther: 'O-ГЕО',
  geoExternal: 'Э-ГЕО',
  geoSchool8: '8Ш-ГЕО',
  geoSchool9: '9Ш-ГЕО',
  geoSchool10: '10Ш-ГЕО',
  geoSchool11: '11Ш-ГЕО',
  geoPract11: '11П-ГЕО',
  soch1: '1-СОЧ',
  soch2: '2-СОЧ',
  soch3: '3-СОЧ',
  soch4: '4-СОЧ',
  soch5: '5-СОЧ',
  soch6: '6-СОЧ',
  soch7: '7-СОЧ',
  soch8: '8-СОЧ',
  soch9: '9-СОЧ',
  soch10: '10-СОЧ',
  soch11: '11-СОЧ',
  sochStudents: 'C-СОЧ',
  sochOther: 'O-СОЧ',
  sochExternal: 'Э-СОЧ',
  sochSchool8: '8Ш-СОЧ',
  sochSchool9: '9Ш-СОЧ',
  sochSchool10: '10Ш-СОЧ',
  sochSchool11: '11Ш-СОЧ',
  sochPract11: '11П-СОЧ',
  infOge1: '1-ИНФ-OГЭ',
  infOge2: '2-ИНФ-OГЭ',
  infOge3: '3-ИНФ-OГЭ',
  infOge4: '4-ИНФ-OГЭ',
  infOge5: '5-ИНФ-OГЭ',
  infOge6: '6-ИНФ-OГЭ',
  infOge7: '7-ИНФ-OГЭ',
  infOge8: '8-ИНФ-OГЭ',
  infOge9: '9-ИНФ-OГЭ',
  infOge10: '10-ИНФ-OГЭ',
  infOge11: '11-ИНФ-OГЭ',
  infOgeStudents: 'C-ИНФ-OГЭ',
  infOgeOther: 'O-ИНФ-OГЭ',
  infOgeExternal: 'Э-ИНФ-OГЭ',
  infOgeSchool8: '8Ш-ИНФ-OГЭ',
  infOgeSchool9: '9Ш-ИНФ-OГЭ',
  infOgeSchool10: '10Ш-ИНФ-OГЭ',
  infOgeSchool11: '11Ш-ИНФ-OГЭ',
  infOgePract11: '11П-ИНФ-OГЭ',
  physOge1: '1-ФИЗ-OГЭ',
  physOge2: '2-ФИЗ-OГЭ',
  physOge3: '3-ФИЗ-OГЭ',
  physOge4: '4-ФИЗ-OГЭ',
  physOge5: '5-ФИЗ-OГЭ',
  physOge6: '6-ФИЗ-OГЭ',
  physOge7: '7-ФИЗ-OГЭ',
  physOge8: '8-ФИЗ-OГЭ',
  physOge9: '9-ФИЗ-OГЭ',
  physOge10: '10-ФИЗ-OГЭ',
  physOge11: '11-ФИЗ-OГЭ',
  physOgeStudents: 'C-ФИЗ-OГЭ',
  physOgeOther: 'O-ФИЗ-OГЭ',
  physOgeExternal: 'Э-ФИЗ-OГЭ',
  physOgeSchool8: '8Ш-ФИЗ-OГЭ',
  physOgeSchool9: '9Ш-ФИЗ-OГЭ',
  physOgeSchool10: '10Ш-ФИЗ-OГЭ',
  physOgeSchool11: '11Ш-ФИЗ-OГЭ',
  physOgePract11: '11П-ФИЗ-OГЭ',
  chemOge1: '1-ХИМ-OГЭ',
  chemOge2: '2-ХИМ-OГЭ',
  chemOge3: '3-ХИМ-OГЭ',
  chemOge4: '4-ХИМ-OГЭ',
  chemOge5: '5-ХИМ-OГЭ',
  chemOge6: '6-ХИМ-OГЭ',
  chemOge7: '7-ХИМ-OГЭ',
  chemOge8: '8-ХИМ-OГЭ',
  chemOge9: '9-ХИМ-OГЭ',
  chemOge10: '10-ХИМ-OГЭ',
  chemOge11: '11-ХИМ-OГЭ',
  chemOgeStudents: 'C-ХИМ-OГЭ',
  chemOgeOther: 'O-ХИМ-OГЭ',
  chemOgeExternal: 'Э-ХИМ-OГЭ',
  chemOgeSchool8: '8Ш-ХИМ-OГЭ',
  chemOgeSchool9: '9Ш-ХИМ-OГЭ',
  chemOgeSchool10: '10Ш-ХИМ-OГЭ',
  chemOgeSchool11: '11Ш-ХИМ-OГЭ',
  chemOgePract11: '11П-ХИМ-OГЭ',
  bioOge1: '1-БИО-OГЭ',
  bioOge2: '2-БИО-OГЭ',
  bioOge3: '3-БИО-OГЭ',
  bioOge4: '4-БИО-OГЭ',
  bioOge5: '5-БИО-OГЭ',
  bioOge6: '6-БИО-OГЭ',
  bioOge7: '7-БИО-OГЭ',
  bioOge8: '8-БИО-OГЭ',
  bioOge9: '9-БИО-OГЭ',
  bioOge10: '10-БИО-OГЭ',
  bioOge11: '11-БИО-OГЭ',
  bioOgeStudents: 'C-БИО-OГЭ',
  bioOgeOther: 'O-БИО-OГЭ',
  bioOgeExternal: 'Э-БИО-OГЭ',
  bioOgeSchool8: '8Ш-БИО-OГЭ',
  bioOgeSchool9: '9Ш-БИО-OГЭ',
  bioOgeSchool10: '10Ш-БИО-OГЭ',
  bioOgeSchool11: '11Ш-БИО-OГЭ',
  bioOgePract11: '11П-БИО-OГЭ',
  litOge1: '1-ЛИТ-OГЭ',
  litOge2: '2-ЛИТ-OГЭ',
  litOge3: '3-ЛИТ-OГЭ',
  litOge4: '4-ЛИТ-OГЭ',
  litOge5: '5-ЛИТ-OГЭ',
  litOge6: '6-ЛИТ-OГЭ',
  litOge7: '7-ЛИТ-OГЭ',
  litOge8: '8-ЛИТ-OГЭ',
  litOge9: '9-ЛИТ-OГЭ',
  litOge10: '10-ЛИТ-OГЭ',
  litOge11: '11-ЛИТ-OГЭ',
  litOgeStudents: 'C-ЛИТ-OГЭ',
  litOgeOther: 'O-ЛИТ-OГЭ',
  litOgeExternal: 'Э-ЛИТ-OГЭ',
  litOgeSchool8: '8Ш-ЛИТ-OГЭ',
  litOgeSchool9: '9Ш-ЛИТ-OГЭ',
  litOgeSchool10: '10Ш-ЛИТ-OГЭ',
  litOgeSchool11: '11Ш-ЛИТ-OГЭ',
  litOgePract11: '11П-ЛИТ-OГЭ',
  engOge1: '1-АНГ-OГЭ',
  engOge2: '2-АНГ-OГЭ',
  engOge3: '3-АНГ-OГЭ',
  engOge4: '4-АНГ-OГЭ',
  engOge5: '5-АНГ-OГЭ',
  engOge6: '6-АНГ-OГЭ',
  engOge7: '7-АНГ-OГЭ',
  engOge8: '8-АНГ-OГЭ',
  engOge9: '9-АНГ-OГЭ',
  engOge10: '10-АНГ-OГЭ',
  engOge11: '11-АНГ-OГЭ',
  engOgeStudents: 'C-АНГ-OГЭ',
  engOgeOther: 'O-АНГ-OГЭ',
  engOgeExternal: 'Э-АНГ-OГЭ',
  engOgeSchool8: '8Ш-АНГ-OГЭ',
  engOgeSchool9: '9Ш-АНГ-OГЭ',
  engOgeSchool10: '10Ш-АНГ-OГЭ',
  engOgeSchool11: '11Ш-АНГ-OГЭ',
  engOgePract11: '11П-АНГ-OГЭ',
  socOge1: '1-ОБЩ-OГЭ',
  socOge2: '2-ОБЩ-OГЭ',
  socOge3: '3-ОБЩ-OГЭ',
  socOge4: '4-ОБЩ-OГЭ',
  socOge5: '5-ОБЩ-OГЭ',
  socOge6: '6-ОБЩ-OГЭ',
  socOge7: '7-ОБЩ-OГЭ',
  socOge8: '8-ОБЩ-OГЭ',
  socOge9: '9-ОБЩ-OГЭ',
  socOge10: '10-ОБЩ-OГЭ',
  socOge11: '11-ОБЩ-OГЭ',
  socOgeStudents: 'C-ОБЩ-OГЭ',
  socOgeOther: 'O-ОБЩ-OГЭ',
  socOgeExternal: 'Э-ОБЩ-OГЭ',
  socOgeSchool8: '8Ш-ОБЩ-OГЭ',
  socOgeSchool9: '9Ш-ОБЩ-OГЭ',
  socOgeSchool10: '10Ш-ОБЩ-OГЭ',
  socOgeSchool11: '11Ш-ОБЩ-OГЭ',
  socOgePract11: '11П-ОБЩ-OГЭ',
  hisOge1: '1-ИСТ-OГЭ',
  hisOge2: '2-ИСТ-OГЭ',
  hisOge3: '3-ИСТ-OГЭ',
  hisOge4: '4-ИСТ-OГЭ',
  hisOge5: '5-ИСТ-OГЭ',
  hisOge6: '6-ИСТ-OГЭ',
  hisOge7: '7-ИСТ-OГЭ',
  hisOge8: '8-ИСТ-OГЭ',
  hisOge9: '9-ИСТ-OГЭ',
  hisOge10: '10-ИСТ-OГЭ',
  hisOge11: '11-ИСТ-OГЭ',
  hisOgeStudents: 'C-ИСТ-OГЭ',
  hisOgeOther: 'O-ИСТ-OГЭ',
  hisOgeExternal: 'Э-ИСТ-OГЭ',
  hisOgeSchool8: '8Ш-ИСТ-OГЭ',
  hisOgeSchool9: '9Ш-ИСТ-OГЭ',
  hisOgeSchool10: '10Ш-ИСТ-OГЭ',
  hisOgeSchool11: '11Ш-ИСТ-OГЭ',
  hisOgePract11: '11П-ИСТ-OГЭ',
  mathProf1: '1-МАТ-ПРО',
  mathProf2: '2-МАТ-ПРО',
  mathProf3: '3-МАТ-ПРО',
  mathProf4: '4-МАТ-ПРО',
  mathProf5: '5-МАТ-ПРО',
  mathProf6: '6-МАТ-ПРО',
  mathProf7: '7-МАТ-ПРО',
  mathProf8: '8-МАТ-ПРО',
  mathProf9: '9-МАТ-ПРО',
  mathProf10: '10-МАТ-ПРО',
  mathProf11: '11-МАТ-ПРО',
  mathProfStudents: 'C-МАТ-ПРО',
  mathProfOther: 'O-МАТ-ПРО',
  mathProfExternal: 'Э-МАТ-ПРО',
  mathProfSchool8: '8Ш-МАТ-ПРО',
  mathProfSchool9: '9Ш-МАТ-ПРО',
  mathProfSchool10: '10Ш-МАТ-ПРО',
  mathProfSchool11: '11Ш-МАТ-ПРО',
  mathProfPract11: '11П-МАТ-ПРО',
  mathBase1: '1-МАТ-БАЗ',
  mathBase2: '2-МАТ-БАЗ',
  mathBase3: '3-МАТ-БАЗ',
  mathBase4: '4-МАТ-БАЗ',
  mathBase5: '5-МАТ-БАЗ',
  mathBase6: '6-МАТ-БАЗ',
  mathBase7: '7-МАТ-БАЗ',
  mathBase8: '8-МАТ-БАЗ',
  mathBase9: '9-МАТ-БАЗ',
  mathBase10: '10-МАТ-БАЗ',
  mathBase11: '11-МАТ-БАЗ',
  mathBaseStudents: 'C-МАТ-БАЗ',
  mathBaseOther: 'O-МАТ-БАЗ',
  mathBaseExternal: 'Э-МАТ-БАЗ',
  mathBaseSchool8: '8Ш-МАТ-БАЗ',
  mathBaseSchool9: '9Ш-МАТ-БАЗ',
  mathBaseSchool10: '10Ш-МАТ-БАЗ',
  mathBaseSchool11: '11Ш-МАТ-БАЗ',
  mathBasePract11: '11П-МАТ-БАЗ',
  mathOnline1: '1-ОНЛ-МАТ',
  mathOnline2: '2-ОНЛ-МАТ',
  mathOnline3: '3-ОНЛ-МАТ',
  mathOnline4: '4-ОНЛ-МАТ',
  mathOnline5: '5-ОНЛ-МАТ',
  mathOnline6: '6-ОНЛ-МАТ',
  mathOnline7: '7-ОНЛ-МАТ',
  mathOnline8: '8-ОНЛ-МАТ',
  mathOnline9: '9-ОНЛ-МАТ',
  mathOnline10: '10-ОНЛ-МАТ',
  mathOnline11: '11-ОНЛ-МАТ',
  mathOnlineStudents: 'C-ОНЛ-МАТ',
  mathOnlineOther: 'O-ОНЛ-МАТ',
  mathOnlineExternal: 'Э-ОНЛ-МАТ',
  mathOnlineSchool8: '8Ш-ОНЛ-МАТ',
  mathOnlineSchool9: '9Ш-ОНЛ-МАТ',
  mathOnlineSchool10: '10Ш-ОНЛ-МАТ',
  mathOnlineSchool11: '11Ш-ОНЛ-МАТ',
  mathOnlinePract11: '11П-ОНЛ-МАТ',
  rusOnline1: '1-ОНЛ-РУС',
  rusOnline2: '2-ОНЛ-РУС',
  rusOnline3: '3-ОНЛ-РУС',
  rusOnline4: '4-ОНЛ-РУС',
  rusOnline5: '5-ОНЛ-РУС',
  rusOnline6: '6-ОНЛ-РУС',
  rusOnline7: '7-ОНЛ-РУС',
  rusOnline8: '8-ОНЛ-РУС',
  rusOnline9: '9-ОНЛ-РУС',
  rusOnline10: '10-ОНЛ-РУС',
  rusOnline11: '11-ОНЛ-РУС',
  rusOnlineStudents: 'C-ОНЛ-РУС',
  rusOnlineOther: 'O-ОНЛ-РУС',
  rusOnlineExternal: 'Э-ОНЛ-РУС',
  rusOnlineSchool8: '8Ш-ОНЛ-РУС',
  rusOnlineSchool9: '9Ш-ОНЛ-РУС',
  rusOnlineSchool10: '10Ш-ОНЛ-РУС',
  rusOnlineSchool11: '11Ш-ОНЛ-РУС',
  rusOnlinePract11: '11П-ОНЛ-РУС',
  socOnline1: '1-ОНЛ-ОБЩ',
  socOnline2: '2-ОНЛ-ОБЩ',
  socOnline3: '3-ОНЛ-ОБЩ',
  socOnline4: '4-ОНЛ-ОБЩ',
  socOnline5: '5-ОНЛ-ОБЩ',
  socOnline6: '6-ОНЛ-ОБЩ',
  socOnline7: '7-ОНЛ-ОБЩ',
  socOnline8: '8-ОНЛ-ОБЩ',
  socOnline9: '9-ОНЛ-ОБЩ',
  socOnline10: '10-ОНЛ-ОБЩ',
  socOnline11: '11-ОНЛ-ОБЩ',
  socOnlineStudents: 'C-ОНЛ-ОБЩ',
  socOnlineOther: 'O-ОНЛ-ОБЩ',
  socOnlineExternal: 'Э-ОНЛ-ОБЩ',
  socOnlineSchool8: '8Ш-ОНЛ-ОБЩ',
  socOnlineSchool9: '9Ш-ОНЛ-ОБЩ',
  socOnlineSchool10: '10Ш-ОНЛ-ОБЩ',
  socOnlineSchool11: '11Ш-ОНЛ-ОБЩ',
  socOnlinePract11: '11П-ОНЛ-ОБЩ',
  mathPracticum1: '1-МАТ-ПРАКТ',
  mathPracticum2: '2-МАТ-ПРАКТ',
  mathPracticum3: '3-МАТ-ПРАКТ',
  mathPracticum4: '4-МАТ-ПРАКТ',
  mathPracticum5: '5-МАТ-ПРАКТ',
  mathPracticum6: '6-МАТ-ПРАКТ',
  mathPracticum7: '7-МАТ-ПРАКТ',
  mathPracticum8: '8-МАТ-ПРАКТ',
  mathPracticum9: '9-МАТ-ПРАКТ',
  mathPracticum10: '10-МАТ-ПРАКТ',
  mathPracticum11: '11-МАТ-ПРАКТ',
  mathPracticumStudents: 'C-МАТ-ПРАКТ',
  mathPracticumOther: 'O-МАТ-ПРАКТ',
  mathPracticumExternal: 'Э-МАТ-ПРАКТ',
  mathPracticumSchool8: '8Ш-МАТ-ПРАКТ',
  mathPracticumSchool9: '9Ш-МАТ-ПРАКТ',
  mathPracticumSchool10: '10Ш-МАТ-ПРАКТ',
  mathPracticumSchool11: '11Ш-МАТ-ПРАКТ',
  mathPracticumPract11: '11П-МАТ-ПРАКТ',
  socPracticum1: '1-ОБЩ-ПРАКТ',
  socPracticum2: '2-ОБЩ-ПРАКТ',
  socPracticum3: '3-ОБЩ-ПРАКТ',
  socPracticum4: '4-ОБЩ-ПРАКТ',
  socPracticum5: '5-ОБЩ-ПРАКТ',
  socPracticum6: '6-ОБЩ-ПРАКТ',
  socPracticum7: '7-ОБЩ-ПРАКТ',
  socPracticum8: '8-ОБЩ-ПРАКТ',
  socPracticum9: '9-ОБЩ-ПРАКТ',
  socPracticum10: '10-ОБЩ-ПРАКТ',
  socPracticum11: '11-ОБЩ-ПРАКТ',
  socPracticumStudents: 'C-ОБЩ-ПРАКТ',
  socPracticumOther: 'O-ОБЩ-ПРАКТ',
  socPracticumExternal: 'Э-ОБЩ-ПРАКТ',
  socPracticumSchool8: '8Ш-ОБЩ-ПРАКТ',
  socPracticumSchool9: '9Ш-ОБЩ-ПРАКТ',
  socPracticumSchool10: '10Ш-ОБЩ-ПРАКТ',
  socPracticumSchool11: '11Ш-ОБЩ-ПРАКТ',
  socPracticumPract11: '11П-ОБЩ-ПРАКТ',
  physPracticum1: '1-ФИЗ-ПРАКТ',
  physPracticum2: '2-ФИЗ-ПРАКТ',
  physPracticum3: '3-ФИЗ-ПРАКТ',
  physPracticum4: '4-ФИЗ-ПРАКТ',
  physPracticum5: '5-ФИЗ-ПРАКТ',
  physPracticum6: '6-ФИЗ-ПРАКТ',
  physPracticum7: '7-ФИЗ-ПРАКТ',
  physPracticum8: '8-ФИЗ-ПРАКТ',
  physPracticum9: '9-ФИЗ-ПРАКТ',
  physPracticum10: '10-ФИЗ-ПРАКТ',
  physPracticum11: '11-ФИЗ-ПРАКТ',
  physPracticumStudents: 'C-ФИЗ-ПРАКТ',
  physPracticumOther: 'O-ФИЗ-ПРАКТ',
  physPracticumExternal: 'Э-ФИЗ-ПРАКТ',
  physPracticumSchool8: '8Ш-ФИЗ-ПРАКТ',
  physPracticumSchool9: '9Ш-ФИЗ-ПРАКТ',
  physPracticumSchool10: '10Ш-ФИЗ-ПРАКТ',
  physPracticumSchool11: '11Ш-ФИЗ-ПРАКТ',
  physPracticumPract11: '11П-ФИЗ-ПРАКТ',
  chemPracticum1: '1-ХИМ-ПРАКТ',
  chemPracticum2: '2-ХИМ-ПРАКТ',
  chemPracticum3: '3-ХИМ-ПРАКТ',
  chemPracticum4: '4-ХИМ-ПРАКТ',
  chemPracticum5: '5-ХИМ-ПРАКТ',
  chemPracticum6: '6-ХИМ-ПРАКТ',
  chemPracticum7: '7-ХИМ-ПРАКТ',
  chemPracticum8: '8-ХИМ-ПРАКТ',
  chemPracticum9: '9-ХИМ-ПРАКТ',
  chemPracticum10: '10-ХИМ-ПРАКТ',
  chemPracticum11: '11-ХИМ-ПРАКТ',
  chemPracticumStudents: 'C-ХИМ-ПРАКТ',
  chemPracticumOther: 'O-ХИМ-ПРАКТ',
  chemPracticumExternal: 'Э-ХИМ-ПРАКТ',
  chemPracticumSchool8: '8Ш-ХИМ-ПРАКТ',
  chemPracticumSchool9: '9Ш-ХИМ-ПРАКТ',
  chemPracticumSchool10: '10Ш-ХИМ-ПРАКТ',
  chemPracticumSchool11: '11Ш-ХИМ-ПРАКТ',
  chemPracticumPract11: '11П-ХИМ-ПРАКТ',
  bioPracticum1: '1-БИО-ПРАКТ',
  bioPracticum2: '2-БИО-ПРАКТ',
  bioPracticum3: '3-БИО-ПРАКТ',
  bioPracticum4: '4-БИО-ПРАКТ',
  bioPracticum5: '5-БИО-ПРАКТ',
  bioPracticum6: '6-БИО-ПРАКТ',
  bioPracticum7: '7-БИО-ПРАКТ',
  bioPracticum8: '8-БИО-ПРАКТ',
  bioPracticum9: '9-БИО-ПРАКТ',
  bioPracticum10: '10-БИО-ПРАКТ',
  bioPracticum11: '11-БИО-ПРАКТ',
  bioPracticumStudents: 'C-БИО-ПРАКТ',
  bioPracticumOther: 'O-БИО-ПРАКТ',
  bioPracticumExternal: 'Э-БИО-ПРАКТ',
  bioPracticumSchool8: '8Ш-БИО-ПРАКТ',
  bioPracticumSchool9: '9Ш-БИО-ПРАКТ',
  bioPracticumSchool10: '10Ш-БИО-ПРАКТ',
  bioPracticumSchool11: '11Ш-БИО-ПРАКТ',
  bioPracticumPract11: '11П-БИО-ПРАКТ',
  infPracticum1: '1-ИНФ-ПРАКТ',
  infPracticum2: '2-ИНФ-ПРАКТ',
  infPracticum3: '3-ИНФ-ПРАКТ',
  infPracticum4: '4-ИНФ-ПРАКТ',
  infPracticum5: '5-ИНФ-ПРАКТ',
  infPracticum6: '6-ИНФ-ПРАКТ',
  infPracticum7: '7-ИНФ-ПРАКТ',
  infPracticum8: '8-ИНФ-ПРАКТ',
  infPracticum9: '9-ИНФ-ПРАКТ',
  infPracticum10: '10-ИНФ-ПРАКТ',
  infPracticum11: '11-ИНФ-ПРАКТ',
  infPracticumStudents: 'C-ИНФ-ПРАКТ',
  infPracticumOther: 'O-ИНФ-ПРАКТ',
  infPracticumExternal: 'Э-ИНФ-ПРАКТ',
  infPracticumSchool8: '8Ш-ИНФ-ПРАКТ',
  infPracticumSchool9: '9Ш-ИНФ-ПРАКТ',
  infPracticumSchool10: '10Ш-ИНФ-ПРАКТ',
  infPracticumSchool11: '11Ш-ИНФ-ПРАКТ',
  infPracticumPract11: '11П-ИНФ-ПРАКТ',
  rusPracticum1: '1-РУС-ПРАКТ',
  rusPracticum2: '2-РУС-ПРАКТ',
  rusPracticum3: '3-РУС-ПРАКТ',
  rusPracticum4: '4-РУС-ПРАКТ',
  rusPracticum5: '5-РУС-ПРАКТ',
  rusPracticum6: '6-РУС-ПРАКТ',
  rusPracticum7: '7-РУС-ПРАКТ',
  rusPracticum8: '8-РУС-ПРАКТ',
  rusPracticum9: '9-РУС-ПРАКТ',
  rusPracticum10: '10-РУС-ПРАКТ',
  rusPracticum11: '11-РУС-ПРАКТ',
  rusPracticumStudents: 'C-РУС-ПРАКТ',
  rusPracticumOther: 'O-РУС-ПРАКТ',
  rusPracticumExternal: 'Э-РУС-ПРАКТ',
  rusPracticumSchool8: '8Ш-РУС-ПРАКТ',
  rusPracticumSchool9: '9Ш-РУС-ПРАКТ',
  rusPracticumSchool10: '10Ш-РУС-ПРАКТ',
  rusPracticumSchool11: '11Ш-РУС-ПРАКТ',
  rusPracticumPract11: '11П-РУС-ПРАКТ',
  hisPracticum1: '1-ИСТ-ПРАКТ',
  hisPracticum2: '2-ИСТ-ПРАКТ',
  hisPracticum3: '3-ИСТ-ПРАКТ',
  hisPracticum4: '4-ИСТ-ПРАКТ',
  hisPracticum5: '5-ИСТ-ПРАКТ',
  hisPracticum6: '6-ИСТ-ПРАКТ',
  hisPracticum7: '7-ИСТ-ПРАКТ',
  hisPracticum8: '8-ИСТ-ПРАКТ',
  hisPracticum9: '9-ИСТ-ПРАКТ',
  hisPracticum10: '10-ИСТ-ПРАКТ',
  hisPracticum11: '11-ИСТ-ПРАКТ',
  hisPracticumStudents: 'C-ИСТ-ПРАКТ',
  hisPracticumOther: 'O-ИСТ-ПРАКТ',
  hisPracticumExternal: 'Э-ИСТ-ПРАКТ',
  hisPracticumSchool8: '8Ш-ИСТ-ПРАКТ',
  hisPracticumSchool9: '9Ш-ИСТ-ПРАКТ',
  hisPracticumSchool10: '10Ш-ИСТ-ПРАКТ',
  hisPracticumSchool11: '11Ш-ИСТ-ПРАКТ',
  hisPracticumPract11: '11П-ИСТ-ПРАКТ',
  engPracticum1: '1-АНГ-ПРАКТ',
  engPracticum2: '2-АНГ-ПРАКТ',
  engPracticum3: '3-АНГ-ПРАКТ',
  engPracticum4: '4-АНГ-ПРАКТ',
  engPracticum5: '5-АНГ-ПРАКТ',
  engPracticum6: '6-АНГ-ПРАКТ',
  engPracticum7: '7-АНГ-ПРАКТ',
  engPracticum8: '8-АНГ-ПРАКТ',
  engPracticum9: '9-АНГ-ПРАКТ',
  engPracticum10: '10-АНГ-ПРАКТ',
  engPracticum11: '11-АНГ-ПРАКТ',
  engPracticumStudents: 'C-АНГ-ПРАКТ',
  engPracticumOther: 'O-АНГ-ПРАКТ',
  engPracticumExternal: 'Э-АНГ-ПРАКТ',
  engPracticumSchool8: '8Ш-АНГ-ПРАКТ',
  engPracticumSchool9: '9Ш-АНГ-ПРАКТ',
  engPracticumSchool10: '10Ш-АНГ-ПРАКТ',
  engPracticumSchool11: '11Ш-АНГ-ПРАКТ',
  engPracticumPract11: '11П-АНГ-ПРАКТ',
  geoPracticum1: '1-ГЕО-ПРАКТ',
  geoPracticum2: '2-ГЕО-ПРАКТ',
  geoPracticum3: '3-ГЕО-ПРАКТ',
  geoPracticum4: '4-ГЕО-ПРАКТ',
  geoPracticum5: '5-ГЕО-ПРАКТ',
  geoPracticum6: '6-ГЕО-ПРАКТ',
  geoPracticum7: '7-ГЕО-ПРАКТ',
  geoPracticum8: '8-ГЕО-ПРАКТ',
  geoPracticum9: '9-ГЕО-ПРАКТ',
  geoPracticum10: '10-ГЕО-ПРАКТ',
  geoPracticum11: '11-ГЕО-ПРАКТ',
  geoPracticumStudents: 'C-ГЕО-ПРАКТ',
  geoPracticumOther: 'O-ГЕО-ПРАКТ',
  geoPracticumExternal: 'Э-ГЕО-ПРАКТ',
  geoPracticumSchool8: '8Ш-ГЕО-ПРАКТ',
  geoPracticumSchool9: '9Ш-ГЕО-ПРАКТ',
  geoPracticumSchool10: '10Ш-ГЕО-ПРАКТ',
  geoPracticumSchool11: '11Ш-ГЕО-ПРАКТ',
  geoPracticumPract11: '11П-ГЕО-ПРАКТ',
  izl1: '1-ИЗЛ',
  izl2: '2-ИЗЛ',
  izl3: '3-ИЗЛ',
  izl4: '4-ИЗЛ',
  izl5: '5-ИЗЛ',
  izl6: '6-ИЗЛ',
  izl7: '7-ИЗЛ',
  izl8: '8-ИЗЛ',
  izl9: '9-ИЗЛ',
  izl10: '10-ИЗЛ',
  izl11: '11-ИЗЛ',
  izlStudents: 'C-ИЗЛ',
  izlOther: 'O-ИЗЛ',
  izlExternal: 'Э-ИЗЛ',
  izlSchool8: '8Ш-ИЗЛ',
  izlSchool9: '9Ш-ИЗЛ',
  izlSchool10: '10Ш-ИЗЛ',
  izlSchool11: '11Ш-ИЗЛ',
  izlPract11: '11П-ИЗЛ',
  geoOge1: '1-ГЕО-OГЭ',
  geoOge2: '2-ГЕО-OГЭ',
  geoOge3: '3-ГЕО-OГЭ',
  geoOge4: '4-ГЕО-OГЭ',
  geoOge5: '5-ГЕО-OГЭ',
  geoOge6: '6-ГЕО-OГЭ',
  geoOge7: '7-ГЕО-OГЭ',
  geoOge8: '8-ГЕО-OГЭ',
  geoOge9: '9-ГЕО-OГЭ',
  geoOge10: '10-ГЕО-OГЭ',
  geoOge11: '11-ГЕО-OГЭ',
  geoOgeStudents: 'C-ГЕО-OГЭ',
  geoOgeOther: 'O-ГЕО-OГЭ',
  geoOgeExternal: 'Э-ГЕО-OГЭ',
  geoOgeSchool8: '8Ш-ГЕО-OГЭ',
  geoOgeSchool9: '9Ш-ГЕО-OГЭ',
  geoOgeSchool10: '10Ш-ГЕО-OГЭ',
  geoOgeSchool11: '11Ш-ГЕО-OГЭ',
  geoOgePract11: '11П-ГЕО-OГЭ',
  engSpoken1: '1-АНГ-Р',
  engSpoken2: '2-АНГ-Р',
  engSpoken3: '3-АНГ-Р',
  engSpoken4: '4-АНГ-Р',
  engSpoken5: '5-АНГ-Р',
  engSpoken6: '6-АНГ-Р',
  engSpoken7: '7-АНГ-Р',
  engSpoken8: '8-АНГ-Р',
  engSpoken9: '9-АНГ-Р',
  engSpoken10: '10-АНГ-Р',
  engSpoken11: '11-АНГ-Р',
  engSpokenStudents: 'C-АНГ-Р',
  engSpokenOther: 'O-АНГ-Р',
  engSpokenExternal: 'Э-АНГ-Р',
  engSpokenSchool8: '8Ш-АНГ-Р',
  engSpokenSchool9: '9Ш-АНГ-Р',
  engSpokenSchool10: '10Ш-АНГ-Р',
  engSpokenSchool11: '11Ш-АНГ-Р',
  engSpokenPract11: '11П-АНГ-Р',
} as const

export const BranchLabel = {
  ohr: 'ОХР',
  pvn: 'ВЕР',
  bgt: 'БАГ',
  izm: 'ИЗМ',
  opl: 'ОКТ',
  rpt: 'РЯЗ',
  skl: 'СКЛ',
  orh: 'ОРЕ',
  ann: 'АНН',
  per: 'ПЕР',
  klg: 'КЛЖ',
  brt: 'БРА',
  str: 'СТР',
  vld: 'ВЛА',
  bel: 'БЕЛ',
  bib: 'БИБ',
  svi: 'СВИ',
  nag: 'НАГ',
  sok: 'СОК',
  pla: 'ПЛА',
  vod: 'ВОД',
  trg: 'ТУР',
} as const

export const RequestStatusLabel = {
  new: 'новые',
  awaiting: 'в ожидании',
  finished: 'выполненные',
  trash: 'архив',
} as const

export const WeekdayLabel = {
  0: 'пн',
  1: 'вт',
  2: 'ср',
  3: 'чт',
  4: 'пт',
  5: 'сб',
  6: 'вс',
} as const

export const LessonStatusLabel = {
  planned: 'планируется',
  conducted: 'проведено',
  cancelled: 'отменено',
} as const

export const ClientLessonStatusLabel = {
  present: 'был',
  late: 'опоздал',
  absent: 'не был',
} as const

export const QuarterLabel = {
  q1: '1 четверть',
  q2: '2 четверть',
  q3: '3 четверть',
  q4: '4 четверть',
  final: 'итоговая',
} as const

export const MonthLabel = {
  1: 'январь',
  2: 'февраль',
  3: 'март',
  4: 'апрель',
  5: 'май',
  6: 'июнь',
  7: 'июль',
  8: 'август',
  9: 'сентябрь',
  10: 'октябрь',
  11: 'ноябрь',
  12: 'декабрь',
} as const

export const MonthLabelShort = {
  1: 'янв',
  2: 'фев',
  3: 'мар',
  4: 'апр',
  5: 'мая',
  6: 'июн',
  7: 'июл',
  8: 'авг',
  9: 'сен',
  10: 'окт',
  11: 'ноя',
  12: 'дек',
} as const

// export const MonthLabelDative = [
//   'января',
//   'февраля',
//   'марта',
//   'апреля',
//   'мая',
//   'июня',
//   'июля',
//   'августа',
//   'сентября',
//   'октября',
//   'ноября',
//   'декабря',
// ] as const

export const EntityTypeValue = {
  request: 'App\\Models\\Request',
  client: 'App\\Models\\Client',
  clientParent: 'App\\Models\\ClientParent',
  contract: 'App\\Models\\Contract',
  teacher: 'App\\Models\\Teacher',
  user: 'App\\Models\\User',
  group: 'App\\Models\\Group',
} as const

export const EntityTypeLabel = {
  'App\\Models\\Request': 'заявка',
  'App\\Models\\Client': 'клиент',
  'App\\Models\\ClientParent': 'родитель',
  'App\\Models\\Contract': 'договор',
  'App\\Models\\Teacher': 'преподаватель',
  'App\\Models\\User': 'администратор',
  'App\\Models\\Group': 'группа',
} as const

export const LessonScoreLabel = {
  5: 'пять',
  4: 'четыре',
  3: 'три',
  2: 'два',
}

export const YearLabel = {
  2024: '2024–2025 уч. г.',
  2023: '2023–2024 уч. г.',
  2022: '2022–2023 уч. г.',
  2021: '2021–2022 уч. г.',
  2020: '2020–2021 уч. г.',
  2019: '2019–2020 уч. г.',
  2018: '2018–2019 уч. г.',
  2017: '2017–2018 уч. г.',
  2016: '2016–2017 уч. г.',
  2015: '2015–2016 уч. г.',
} as const

/* eslint-disable */
export const CabinetLabel = {
  cab428: "К-428",
  cab430: "К-430",
  cab432: "К-432",
  cab433: "К-433",
  cab434: "К-434",
  cab439: "К-439",
  cab407: "К-407",
  cab409: "К-409",
  cab412: "К-412",
  cab413: "К-413",
  cab414: "К-414",
  cab417: "К-417",
  cab418: "К-418",
  cab420: "К-420",
  cab422: "К-422",
  cab423: "К-423",
  cab424: "К-424",
  cab310: "К-310",
  cab312: "К-312",
  cab314: "К-314",
  cab316: "К-316",
  tur10: "ТУР-10",
  tur35: "ТУР-35",
  tur205: "ТУР-205",
  tur214: "ТУР-214",
  tur221: "ТУР-221",
  tur301: "ТУР-301",
  tur302: "ТУР-302",
  tur303: "ТУР-303",
  tur304: "ТУР-304",
  tur305: "ТУР-305",
  tur310: "ТУР-310",
  tur311: "ТУР-311",
  tur314: "ТУР-314",
  tur319: "ТУР-319",
  tur320: "ТУР-320",
  tur321: "ТУР-321",
  tur322: "ТУР-322",
  tur507: "ТУР-507",
  tur809: "ТУР-809"
} as const;
/* eslint-enable */

export const TeacherStatusLabel = {
  inactive: 'неактивен',
  active: 'ведет занятия сейчас',
  earlyReserve: 'ранний запас',
  lateReserve: 'поздний запас',
  usedToWork: 'ранее работал',
  interview: 'собеседование',
  closed: 'закрыт',
} as const

export const UserStatusLabel: { [key: number]: string } = {
  1: 'действующий сотрудник',
  0: 'больше не работает',
}

export const SubjectLabel = {
  math: 'математика',
  phys: 'физика',
  chem: 'химия',
  bio: 'биология',
  inf: 'информатика',
  rus: 'русский язык',
  lit: 'литература',
  soc: 'обществознание',
  his: 'история',
  eng: 'английский язык',
  geo: 'география',
  soch: 'сочинение',
} as const

export const SubjectLabelShort = {
  math: 'МАТ',
  phys: 'ФИЗ',
  chem: 'ХИМ',
  bio: 'БИО',
  inf: 'ИНФ',
  rus: 'РУС',
  lit: 'ЛИТ',
  soc: 'ОБЩ',
  his: 'ИСТ',
  eng: 'АНГ',
  geo: 'ГЕО',
  soch: 'СОЧ',
} as const

export const TeacherPaymentMethodLabel = {
  card: 'карта',
  cash: 'наличные',
  invoice: 'счёт',
  mutual: 'взаимозачёт',
} as const

export const ContractPaymentMethodLabel = {
  card: 'карта',
  online: 'карта онлайн',
  cash: 'наличные',
  invoice: 'счёт',
} as const

export const ClientPaymentMethodLabel = {
  card: 'карта',
  cash: 'наличные',
} as const

export const CompanyLabel = {
  ooo: 'ООО',
  ip: 'ИП',
} as const

export const ExamLabel = {
  ogeMath: 'ОГЭ математика',
  ogePhys: 'ОГЭ физика',
  ogeChem: 'ОГЭ химия',
  ogeBio: 'ОГЭ биология',
  ogeEng: 'ОГЭ английский',
  ogeInf: 'ОГЭ информатика',
  ogeRus: 'ОГЭ русский',
  ogeLit: 'ОГЭ литература',
  ogeGeo: 'ОГЭ география',
  ogeHis: 'ОГЭ история',
  ogeSoc: 'ОГЭ обществознание',
  egeMathBase: 'ЕГЭ математика база',
  egeMathProf: 'ЕГЭ математика профиль',
  egePhys: 'ЕГЭ физика',
  egeChem: 'ЕГЭ химия',
  egeBio: 'ЕГЭ биология',
  egeEng: 'ЕГЭ английский',
  egeInf: 'ЕГЭ информатика',
  egeRus: 'ЕГЭ русский',
  egeLit: 'ЕГЭ литература',
  egeGeo: 'ЕГЭ география',
  egeHis: 'ЕГЭ история',
  egeSoc: 'ЕГЭ обществознание',
}

export const StatsModeLabel = {
  day: 'по дням',
  month: 'по месяцам',
  year: 'по годам',
} as const

export const LogTypeLabel = {
  create: 'создание',
  update: 'обновление',
  delete: 'удаление',
  view: 'просмотр',
  auth: 'авторизация',
} as const

export const LogTableLabel = {
  client_payments: 'client_payments',
  client_reviews: 'client_reviews',
  client_tests: 'client_tests',
  comments: 'comments',
  client_lessons: 'client_lessons',
  contract_version_payments: 'contract_version_payments',
  contract_version_programs: 'contract_version_programs',
  contract_versions: 'contract_versions',
  contracts: 'contracts',
  event_participants: 'event_participants',
  events: 'events',
  grades: 'grades',
  groups: 'groups',
  lessons: 'lessons',
  reports: 'reports',
  telegram_messages: 'telegram_messages',
  tests: 'tests',
  vacations: 'vacations',
} as const

export const ClientTestStatusLabel = {
  new: 'не пройден',
  active: 'активен',
  finished: 'завершен',
} as const

export const CallAppStatusFilterLabel = {
  all: 'все звонки',
  missed: 'пропущенные',
  active: 'активные',
  outgoing: 'исходящие',
} as const

export const SwampFilterStatusLabel = {
  toFulfil: 'к исполнению',
  exceedNoGroup: 'избыток по услугам + не в группе',
  completeNoGroup: 'исполнено + не в группе',
  inProcess: 'исполняется',
  exceedInGroup: 'избыток по услугам + в группе',
  completeInGroup: 'исполнено + в группе',
} as const

export const SendToLabel = {
  studentsAndParents: 'ученикам и родителям',
  students: 'только ученикам',
  parents: 'только родителям',
} as const

export const EventParticipantConfirmationLabel = {
  pending: 'не подтвердил участие',
  confirmed: 'подтвердил участие',
  rejected: 'отказался от участия',
} as const

export const TelegramListStatusLabel = {
  scheduled: 'запланировано',
  sending: 'отправляется',
  sent: 'отправлено',
} as const

export const ErrorCodeLabel = [1000] as const

export const PassTypeLabel = {
  person: 'на человека',
  car: 'на машину',
} as const

export const PassStatusLabel = {
  active: 'не использован',
  used: 'использован',
  expired: 'истёк',
} as const

export const RequestDirectionLabel = {
  courses9: 'курсы-9',
  courses10: 'курсы-10',
  courses11: 'курсы-11',
  school8: 'школа-8',
  school9: 'школа-9',
  school10: 'школа-10',
  school11: 'школа-11',
  external: 'экстернат',
  practicum: 'практикум',
  egeTrial: 'пробный ЕГЭ',
  python: 'python',
  english: 'английский',
  online: 'онлайн',
} as const
