export const ProgramLabel = {
  math9: 'математика 9 класс',
  phys9: 'физика 9 класс',
  chem9: 'химия 9 класс',
  bio9: 'биология 9 класс',
  inf9: 'информатика 9 класс',
  rus9: 'русский 9 класс',
  lit9: 'литература 9 класс',
  soc9: 'обществознание 9 класс',
  his9: 'история 9 класс',
  eng9: 'английский 9 класс',
  geo9: 'география 9 класс',
  essay9: 'итоговое сочинение',

  math10: 'математика 10 класс',
  phys10: 'физика 10 класс',
  chem10: 'химия 10 класс',
  bio10: 'биология 10 класс',
  inf10: 'информатика 10 класс',
  rus10: 'русский язык 10 класс',
  lit10: 'литература 10 класс',
  soc10: 'обществознание 10 класс',
  his10: 'история 10 класс',
  eng10: 'английский язык 10 класс',

  math11: 'математика 11 класс',
  phys11: 'физика 11 класс',
  chem11: 'химия 11 класс',
  bio11: 'биология 11 класс',
  inf11: 'информатика 11 класс',
  rus11: 'русский язык 11 класс',
  lit11: 'литература 11 класс',
  soc11: 'обществознание 11 класс',
  his11: 'история 11 класс',
  eng11: 'английский язык 11 класс',
  geo11: 'география 11 класс',
  essay11: 'итоговое собеседование',

  mathSchool8: 'математика школа 8 класс',
  physSchool8: 'физика школа 8 класс',
  chemSchool8: 'химия школа 8 класс',
  bioSchool8: 'биология школа 8 класс',
  infSchool8: 'информатика школа 8 класс',
  rusSchool8: 'русский язык школа 8 класс',
  litSchool8: 'литература школа 8 класс',
  socSchool8: 'обществознание школа 8 класс',
  hisSchool8: 'история школа 8 класс',
  engSchool8: 'английский язык школа 8 класс',
  geoSchool8: 'география школа 8 класс',

  mathSchool9: 'математика школа 9 класс',
  physSchool9: 'физика школа 9 класс',
  chemSchool9: 'химия школа 9 класс',
  bioSchool9: 'биология школа 9 класс',
  infSchool9: 'информатика школа 9 класс',
  rusSchool9: 'русский язык школа 9 класс',
  litSchool9: 'литература школа 9 класс',
  socSchool9: 'обществознание школа 9 класс',
  hisSchool9: 'история школа 9 класс',
  engSchool9: 'английский язык школа 9 класс',
  geoSchool9: 'география школа 9 класс',

  mathSchool10: 'математика школа 10 класс',
  physSchool10: 'физика школа 10 класс',
  chemSchool10: 'химия школа 10 класс',
  bioSchool10: 'биология школа 10 класс',
  infSchool10: 'информатика школа 10 класс',
  rusSchool10: 'русский язык школа 10 класс',
  litSchool10: 'литература школа 10 класс',
  socSchool10: 'обществознание школа 10 класс',
  hisSchool10: 'история школа 10 класс',
  engSchool10: 'английский язык школа 10 класс',

  mathSchool11: 'математика школа 11 класс',
  physSchool11: 'физика школа 11 класс',
  chemSchool11: 'химия школа 11 класс',
  bioSchool11: 'биология школа 11 класс',
  infSchool11: 'информатика школа 11 класс',
  rusSchool11: 'русский язык школа 11 класс',
  litSchool11: 'литература школа 11 класс',
  socSchool11: 'обществознание школа 11 класс',
  hisSchool11: 'история школа 11 класс',
  engSchool11: 'английский язык школа 11 класс',

  mathExt: 'математика экстернат',
  physExt: 'физика экстернат',
  chemExt: 'химия экстернат',
  bioExt: 'биология экстернат',
  infExt: 'информатика экстернат',
  rusExt: 'русский язык экстернат',
  litExt: 'литература экстернат',
  socExt: 'обществознание экстернат',
  hisExt: 'история экстернат',
  engExt: 'английский язык экстернат',
  geoExt: 'география экстернат',

  physSchoolOge: 'физика школа ОГЭ',
  chemSchoolOge: 'химия школа ОГЭ',
  bioSchoolOge: 'биология школа ОГЭ',
  infSchoolOge: 'информатика школа ОГЭ',
  litSchoolOge: 'литература школа ОГЭ',
  socSchoolOge: 'обществознание школа ОГЭ',
  hisSchoolOge: 'история школа ОГЭ',
  engSchoolOge: 'английский язык школа ОГЭ',

  mathPracticum: 'математика практикум',
  physPracticum: 'физика практикум',
  chemPracticum: 'химия практикум',
  bioPracticum: 'биология практикум',
  infPracticum: 'информатика практикум',
  rusPracticum: 'русский язык практикум',
  socPracticum: 'обществознание практикум',
  hisPracticum: 'история практикум',
  engPracticum: 'английский язык практикум',
  geoPracticum: 'география практикум',

  mathBase: 'математика база',
  mathProf: 'математика профиль',
} as const

export const TelegramTemplateLabel = {
  reportPublished: 'отчёт отправлен',
  reportRead: 'отчёт прочитан',
  clientLessonStatus: 'опоздал/не пришёл',
}

export const ProgramShortLabel = {
  math1: '1-МАТ',
  math2: '2-МАТ',
  math3: '3-МАТ',
  math4: '4-МАТ',
  math5: '5-МАТ',
  math6: '6-МАТ',
  math7: '7-МАТ',
  math8: '8-МАТ',
  math9: '9-МАТ',
  math10: '10-МАТ',
  math11: '11-МАТ',
  mathStudents: 'C-МАТ',
  mathOther: 'O-МАТ',
  mathExternal: 'Э-МАТ',
  mathSchool8: '8Ш-МАТ',
  mathSchool9: '9Ш-МАТ',
  mathSchool10: '10Ш-МАТ',
  mathSchool11: '11Ш-МАТ',
  mathPract11: '11П-МАТ',
  phys1: '1-ФИЗ',
  phys2: '2-ФИЗ',
  phys3: '3-ФИЗ',
  phys4: '4-ФИЗ',
  phys5: '5-ФИЗ',
  phys6: '6-ФИЗ',
  phys7: '7-ФИЗ',
  phys8: '8-ФИЗ',
  phys9: '9-ФИЗ',
  phys10: '10-ФИЗ',
  phys11: '11-ФИЗ',
  physStudents: 'C-ФИЗ',
  physOther: 'O-ФИЗ',
  physExternal: 'Э-ФИЗ',
  physSchool8: '8Ш-ФИЗ',
  physSchool9: '9Ш-ФИЗ',
  physSchool10: '10Ш-ФИЗ',
  physSchool11: '11Ш-ФИЗ',
  physPract11: '11П-ФИЗ',
  chem1: '1-ХИМ',
  chem2: '2-ХИМ',
  chem3: '3-ХИМ',
  chem4: '4-ХИМ',
  chem5: '5-ХИМ',
  chem6: '6-ХИМ',
  chem7: '7-ХИМ',
  chem8: '8-ХИМ',
  chem9: '9-ХИМ',
  chem10: '10-ХИМ',
  chem11: '11-ХИМ',
  chemStudents: 'C-ХИМ',
  chemOther: 'O-ХИМ',
  chemExternal: 'Э-ХИМ',
  chemSchool8: '8Ш-ХИМ',
  chemSchool9: '9Ш-ХИМ',
  chemSchool10: '10Ш-ХИМ',
  chemSchool11: '11Ш-ХИМ',
  chemPract11: '11П-ХИМ',
  bio1: '1-БИО',
  bio2: '2-БИО',
  bio3: '3-БИО',
  bio4: '4-БИО',
  bio5: '5-БИО',
  bio6: '6-БИО',
  bio7: '7-БИО',
  bio8: '8-БИО',
  bio9: '9-БИО',
  bio10: '10-БИО',
  bio11: '11-БИО',
  bioStudents: 'C-БИО',
  bioOther: 'O-БИО',
  bioExternal: 'Э-БИО',
  bioSchool8: '8Ш-БИО',
  bioSchool9: '9Ш-БИО',
  bioSchool10: '10Ш-БИО',
  bioSchool11: '11Ш-БИО',
  bioPract11: '11П-БИО',
  inf1: '1-ИНФ',
  inf2: '2-ИНФ',
  inf3: '3-ИНФ',
  inf4: '4-ИНФ',
  inf5: '5-ИНФ',
  inf6: '6-ИНФ',
  inf7: '7-ИНФ',
  inf8: '8-ИНФ',
  inf9: '9-ИНФ',
  inf10: '10-ИНФ',
  inf11: '11-ИНФ',
  infStudents: 'C-ИНФ',
  infOther: 'O-ИНФ',
  infExternal: 'Э-ИНФ',
  infSchool8: '8Ш-ИНФ',
  infSchool9: '9Ш-ИНФ',
  infSchool10: '10Ш-ИНФ',
  infSchool11: '11Ш-ИНФ',
  infPract11: '11П-ИНФ',
  rus1: '1-РУС',
  rus2: '2-РУС',
  rus3: '3-РУС',
  rus4: '4-РУС',
  rus5: '5-РУС',
  rus6: '6-РУС',
  rus7: '7-РУС',
  rus8: '8-РУС',
  rus9: '9-РУС',
  rus10: '10-РУС',
  rus11: '11-РУС',
  rusStudents: 'C-РУС',
  rusOther: 'O-РУС',
  rusExternal: 'Э-РУС',
  rusSchool8: '8Ш-РУС',
  rusSchool9: '9Ш-РУС',
  rusSchool10: '10Ш-РУС',
  rusSchool11: '11Ш-РУС',
  rusPract11: '11П-РУС',
  lit1: '1-ЛИТ',
  lit2: '2-ЛИТ',
  lit3: '3-ЛИТ',
  lit4: '4-ЛИТ',
  lit5: '5-ЛИТ',
  lit6: '6-ЛИТ',
  lit7: '7-ЛИТ',
  lit8: '8-ЛИТ',
  lit9: '9-ЛИТ',
  lit10: '10-ЛИТ',
  lit11: '11-ЛИТ',
  litStudents: 'C-ЛИТ',
  litOther: 'O-ЛИТ',
  litExternal: 'Э-ЛИТ',
  litSchool8: '8Ш-ЛИТ',
  litSchool9: '9Ш-ЛИТ',
  litSchool10: '10Ш-ЛИТ',
  litSchool11: '11Ш-ЛИТ',
  litPract11: '11П-ЛИТ',
  soc1: '1-ОБЩ',
  soc2: '2-ОБЩ',
  soc3: '3-ОБЩ',
  soc4: '4-ОБЩ',
  soc5: '5-ОБЩ',
  soc6: '6-ОБЩ',
  soc7: '7-ОБЩ',
  soc8: '8-ОБЩ',
  soc9: '9-ОБЩ',
  soc10: '10-ОБЩ',
  soc11: '11-ОБЩ',
  socStudents: 'C-ОБЩ',
  socOther: 'O-ОБЩ',
  socExternal: 'Э-ОБЩ',
  socSchool8: '8Ш-ОБЩ',
  socSchool9: '9Ш-ОБЩ',
  socSchool10: '10Ш-ОБЩ',
  socSchool11: '11Ш-ОБЩ',
  socPract11: '11П-ОБЩ',
  his1: '1-ИСТ',
  his2: '2-ИСТ',
  his3: '3-ИСТ',
  his4: '4-ИСТ',
  his5: '5-ИСТ',
  his6: '6-ИСТ',
  his7: '7-ИСТ',
  his8: '8-ИСТ',
  his9: '9-ИСТ',
  his10: '10-ИСТ',
  his11: '11-ИСТ',
  hisStudents: 'C-ИСТ',
  hisOther: 'O-ИСТ',
  hisExternal: 'Э-ИСТ',
  hisSchool8: '8Ш-ИСТ',
  hisSchool9: '9Ш-ИСТ',
  hisSchool10: '10Ш-ИСТ',
  hisSchool11: '11Ш-ИСТ',
  hisPract11: '11П-ИСТ',
  eng1: '1-АНГ',
  eng2: '2-АНГ',
  eng3: '3-АНГ',
  eng4: '4-АНГ',
  eng5: '5-АНГ',
  eng6: '6-АНГ',
  eng7: '7-АНГ',
  eng8: '8-АНГ',
  eng9: '9-АНГ',
  eng10: '10-АНГ',
  eng11: '11-АНГ',
  engStudents: 'C-АНГ',
  engOther: 'O-АНГ',
  engExternal: 'Э-АНГ',
  engSchool8: '8Ш-АНГ',
  engSchool9: '9Ш-АНГ',
  engSchool10: '10Ш-АНГ',
  engSchool11: '11Ш-АНГ',
  engPract11: '11П-АНГ',
  geo1: '1-ГЕО',
  geo2: '2-ГЕО',
  geo3: '3-ГЕО',
  geo4: '4-ГЕО',
  geo5: '5-ГЕО',
  geo6: '6-ГЕО',
  geo7: '7-ГЕО',
  geo8: '8-ГЕО',
  geo9: '9-ГЕО',
  geo10: '10-ГЕО',
  geo11: '11-ГЕО',
  geoStudents: 'C-ГЕО',
  geoOther: 'O-ГЕО',
  geoExternal: 'Э-ГЕО',
  geoSchool8: '8Ш-ГЕО',
  geoSchool9: '9Ш-ГЕО',
  geoSchool10: '10Ш-ГЕО',
  geoSchool11: '11Ш-ГЕО',
  geoPract11: '11П-ГЕО',
  soch1: '1-СОЧ',
  soch2: '2-СОЧ',
  soch3: '3-СОЧ',
  soch4: '4-СОЧ',
  soch5: '5-СОЧ',
  soch6: '6-СОЧ',
  soch7: '7-СОЧ',
  soch8: '8-СОЧ',
  soch9: '9-СОЧ',
  soch10: '10-СОЧ',
  soch11: '11-СОЧ',
  sochStudents: 'C-СОЧ',
  sochOther: 'O-СОЧ',
  sochExternal: 'Э-СОЧ',
  sochSchool8: '8Ш-СОЧ',
  sochSchool9: '9Ш-СОЧ',
  sochSchool10: '10Ш-СОЧ',
  sochSchool11: '11Ш-СОЧ',
  sochPract11: '11П-СОЧ',
  infOge1: '1-ИНФ-OГЭ',
  infOge2: '2-ИНФ-OГЭ',
  infOge3: '3-ИНФ-OГЭ',
  infOge4: '4-ИНФ-OГЭ',
  infOge5: '5-ИНФ-OГЭ',
  infOge6: '6-ИНФ-OГЭ',
  infOge7: '7-ИНФ-OГЭ',
  infOge8: '8-ИНФ-OГЭ',
  infOge9: '9-ИНФ-OГЭ',
  infOge10: '10-ИНФ-OГЭ',
  infOge11: '11-ИНФ-OГЭ',
  infOgeStudents: 'C-ИНФ-OГЭ',
  infOgeOther: 'O-ИНФ-OГЭ',
  infOgeExternal: 'Э-ИНФ-OГЭ',
  infOgeSchool8: '8Ш-ИНФ-OГЭ',
  infOgeSchool9: '9Ш-ИНФ-OГЭ',
  infOgeSchool10: '10Ш-ИНФ-OГЭ',
  infOgeSchool11: '11Ш-ИНФ-OГЭ',
  infOgePract11: '11П-ИНФ-OГЭ',
  physOge1: '1-ФИЗ-OГЭ',
  physOge2: '2-ФИЗ-OГЭ',
  physOge3: '3-ФИЗ-OГЭ',
  physOge4: '4-ФИЗ-OГЭ',
  physOge5: '5-ФИЗ-OГЭ',
  physOge6: '6-ФИЗ-OГЭ',
  physOge7: '7-ФИЗ-OГЭ',
  physOge8: '8-ФИЗ-OГЭ',
  physOge9: '9-ФИЗ-OГЭ',
  physOge10: '10-ФИЗ-OГЭ',
  physOge11: '11-ФИЗ-OГЭ',
  physOgeStudents: 'C-ФИЗ-OГЭ',
  physOgeOther: 'O-ФИЗ-OГЭ',
  physOgeExternal: 'Э-ФИЗ-OГЭ',
  physOgeSchool8: '8Ш-ФИЗ-OГЭ',
  physOgeSchool9: '9Ш-ФИЗ-OГЭ',
  physOgeSchool10: '10Ш-ФИЗ-OГЭ',
  physOgeSchool11: '11Ш-ФИЗ-OГЭ',
  physOgePract11: '11П-ФИЗ-OГЭ',
  chemOge1: '1-ХИМ-OГЭ',
  chemOge2: '2-ХИМ-OГЭ',
  chemOge3: '3-ХИМ-OГЭ',
  chemOge4: '4-ХИМ-OГЭ',
  chemOge5: '5-ХИМ-OГЭ',
  chemOge6: '6-ХИМ-OГЭ',
  chemOge7: '7-ХИМ-OГЭ',
  chemOge8: '8-ХИМ-OГЭ',
  chemOge9: '9-ХИМ-OГЭ',
  chemOge10: '10-ХИМ-OГЭ',
  chemOge11: '11-ХИМ-OГЭ',
  chemOgeStudents: 'C-ХИМ-OГЭ',
  chemOgeOther: 'O-ХИМ-OГЭ',
  chemOgeExternal: 'Э-ХИМ-OГЭ',
  chemOgeSchool8: '8Ш-ХИМ-OГЭ',
  chemOgeSchool9: '9Ш-ХИМ-OГЭ',
  chemOgeSchool10: '10Ш-ХИМ-OГЭ',
  chemOgeSchool11: '11Ш-ХИМ-OГЭ',
  chemOgePract11: '11П-ХИМ-OГЭ',
  bioOge1: '1-БИО-OГЭ',
  bioOge2: '2-БИО-OГЭ',
  bioOge3: '3-БИО-OГЭ',
  bioOge4: '4-БИО-OГЭ',
  bioOge5: '5-БИО-OГЭ',
  bioOge6: '6-БИО-OГЭ',
  bioOge7: '7-БИО-OГЭ',
  bioOge8: '8-БИО-OГЭ',
  bioOge9: '9-БИО-OГЭ',
  bioOge10: '10-БИО-OГЭ',
  bioOge11: '11-БИО-OГЭ',
  bioOgeStudents: 'C-БИО-OГЭ',
  bioOgeOther: 'O-БИО-OГЭ',
  bioOgeExternal: 'Э-БИО-OГЭ',
  bioOgeSchool8: '8Ш-БИО-OГЭ',
  bioOgeSchool9: '9Ш-БИО-OГЭ',
  bioOgeSchool10: '10Ш-БИО-OГЭ',
  bioOgeSchool11: '11Ш-БИО-OГЭ',
  bioOgePract11: '11П-БИО-OГЭ',
  litOge1: '1-ЛИТ-OГЭ',
  litOge2: '2-ЛИТ-OГЭ',
  litOge3: '3-ЛИТ-OГЭ',
  litOge4: '4-ЛИТ-OГЭ',
  litOge5: '5-ЛИТ-OГЭ',
  litOge6: '6-ЛИТ-OГЭ',
  litOge7: '7-ЛИТ-OГЭ',
  litOge8: '8-ЛИТ-OГЭ',
  litOge9: '9-ЛИТ-OГЭ',
  litOge10: '10-ЛИТ-OГЭ',
  litOge11: '11-ЛИТ-OГЭ',
  litOgeStudents: 'C-ЛИТ-OГЭ',
  litOgeOther: 'O-ЛИТ-OГЭ',
  litOgeExternal: 'Э-ЛИТ-OГЭ',
  litOgeSchool8: '8Ш-ЛИТ-OГЭ',
  litOgeSchool9: '9Ш-ЛИТ-OГЭ',
  litOgeSchool10: '10Ш-ЛИТ-OГЭ',
  litOgeSchool11: '11Ш-ЛИТ-OГЭ',
  litOgePract11: '11П-ЛИТ-OГЭ',
  engOge1: '1-АНГ-OГЭ',
  engOge2: '2-АНГ-OГЭ',
  engOge3: '3-АНГ-OГЭ',
  engOge4: '4-АНГ-OГЭ',
  engOge5: '5-АНГ-OГЭ',
  engOge6: '6-АНГ-OГЭ',
  engOge7: '7-АНГ-OГЭ',
  engOge8: '8-АНГ-OГЭ',
  engOge9: '9-АНГ-OГЭ',
  engOge10: '10-АНГ-OГЭ',
  engOge11: '11-АНГ-OГЭ',
  engOgeStudents: 'C-АНГ-OГЭ',
  engOgeOther: 'O-АНГ-OГЭ',
  engOgeExternal: 'Э-АНГ-OГЭ',
  engOgeSchool8: '8Ш-АНГ-OГЭ',
  engOgeSchool9: '9Ш-АНГ-OГЭ',
  engOgeSchool10: '10Ш-АНГ-OГЭ',
  engOgeSchool11: '11Ш-АНГ-OГЭ',
  engOgePract11: '11П-АНГ-OГЭ',
  socOge1: '1-ОБЩ-OГЭ',
  socOge2: '2-ОБЩ-OГЭ',
  socOge3: '3-ОБЩ-OГЭ',
  socOge4: '4-ОБЩ-OГЭ',
  socOge5: '5-ОБЩ-OГЭ',
  socOge6: '6-ОБЩ-OГЭ',
  socOge7: '7-ОБЩ-OГЭ',
  socOge8: '8-ОБЩ-OГЭ',
  socOge9: '9-ОБЩ-OГЭ',
  socOge10: '10-ОБЩ-OГЭ',
  socOge11: '11-ОБЩ-OГЭ',
  socOgeStudents: 'C-ОБЩ-OГЭ',
  socOgeOther: 'O-ОБЩ-OГЭ',
  socOgeExternal: 'Э-ОБЩ-OГЭ',
  socOgeSchool8: '8Ш-ОБЩ-OГЭ',
  socOgeSchool9: '9Ш-ОБЩ-OГЭ',
  socOgeSchool10: '10Ш-ОБЩ-OГЭ',
  socOgeSchool11: '11Ш-ОБЩ-OГЭ',
  socOgePract11: '11П-ОБЩ-OГЭ',
  hisOge1: '1-ИСТ-OГЭ',
  hisOge2: '2-ИСТ-OГЭ',
  hisOge3: '3-ИСТ-OГЭ',
  hisOge4: '4-ИСТ-OГЭ',
  hisOge5: '5-ИСТ-OГЭ',
  hisOge6: '6-ИСТ-OГЭ',
  hisOge7: '7-ИСТ-OГЭ',
  hisOge8: '8-ИСТ-OГЭ',
  hisOge9: '9-ИСТ-OГЭ',
  hisOge10: '10-ИСТ-OГЭ',
  hisOge11: '11-ИСТ-OГЭ',
  hisOgeStudents: 'C-ИСТ-OГЭ',
  hisOgeOther: 'O-ИСТ-OГЭ',
  hisOgeExternal: 'Э-ИСТ-OГЭ',
  hisOgeSchool8: '8Ш-ИСТ-OГЭ',
  hisOgeSchool9: '9Ш-ИСТ-OГЭ',
  hisOgeSchool10: '10Ш-ИСТ-OГЭ',
  hisOgeSchool11: '11Ш-ИСТ-OГЭ',
  hisOgePract11: '11П-ИСТ-OГЭ',
  mathProf1: '1-МАТ-ПРО',
  mathProf2: '2-МАТ-ПРО',
  mathProf3: '3-МАТ-ПРО',
  mathProf4: '4-МАТ-ПРО',
  mathProf5: '5-МАТ-ПРО',
  mathProf6: '6-МАТ-ПРО',
  mathProf7: '7-МАТ-ПРО',
  mathProf8: '8-МАТ-ПРО',
  mathProf9: '9-МАТ-ПРО',
  mathProf10: '10-МАТ-ПРО',
  mathProf11: '11-МАТ-ПРО',
  mathProfStudents: 'C-МАТ-ПРО',
  mathProfOther: 'O-МАТ-ПРО',
  mathProfExternal: 'Э-МАТ-ПРО',
  mathProfSchool8: '8Ш-МАТ-ПРО',
  mathProfSchool9: '9Ш-МАТ-ПРО',
  mathProfSchool10: '10Ш-МАТ-ПРО',
  mathProfSchool11: '11Ш-МАТ-ПРО',
  mathProfPract11: '11П-МАТ-ПРО',
  mathBase1: '1-МАТ-БАЗ',
  mathBase2: '2-МАТ-БАЗ',
  mathBase3: '3-МАТ-БАЗ',
  mathBase4: '4-МАТ-БАЗ',
  mathBase5: '5-МАТ-БАЗ',
  mathBase6: '6-МАТ-БАЗ',
  mathBase7: '7-МАТ-БАЗ',
  mathBase8: '8-МАТ-БАЗ',
  mathBase9: '9-МАТ-БАЗ',
  mathBase10: '10-МАТ-БАЗ',
  mathBase11: '11-МАТ-БАЗ',
  mathBaseStudents: 'C-МАТ-БАЗ',
  mathBaseOther: 'O-МАТ-БАЗ',
  mathBaseExternal: 'Э-МАТ-БАЗ',
  mathBaseSchool8: '8Ш-МАТ-БАЗ',
  mathBaseSchool9: '9Ш-МАТ-БАЗ',
  mathBaseSchool10: '10Ш-МАТ-БАЗ',
  mathBaseSchool11: '11Ш-МАТ-БАЗ',
  mathBasePract11: '11П-МАТ-БАЗ',
  mathOnline1: '1-ОНЛ-МАТ',
  mathOnline2: '2-ОНЛ-МАТ',
  mathOnline3: '3-ОНЛ-МАТ',
  mathOnline4: '4-ОНЛ-МАТ',
  mathOnline5: '5-ОНЛ-МАТ',
  mathOnline6: '6-ОНЛ-МАТ',
  mathOnline7: '7-ОНЛ-МАТ',
  mathOnline8: '8-ОНЛ-МАТ',
  mathOnline9: '9-ОНЛ-МАТ',
  mathOnline10: '10-ОНЛ-МАТ',
  mathOnline11: '11-ОНЛ-МАТ',
  mathOnlineStudents: 'C-ОНЛ-МАТ',
  mathOnlineOther: 'O-ОНЛ-МАТ',
  mathOnlineExternal: 'Э-ОНЛ-МАТ',
  mathOnlineSchool8: '8Ш-ОНЛ-МАТ',
  mathOnlineSchool9: '9Ш-ОНЛ-МАТ',
  mathOnlineSchool10: '10Ш-ОНЛ-МАТ',
  mathOnlineSchool11: '11Ш-ОНЛ-МАТ',
  mathOnlinePract11: '11П-ОНЛ-МАТ',
  rusOnline1: '1-ОНЛ-РУС',
  rusOnline2: '2-ОНЛ-РУС',
  rusOnline3: '3-ОНЛ-РУС',
  rusOnline4: '4-ОНЛ-РУС',
  rusOnline5: '5-ОНЛ-РУС',
  rusOnline6: '6-ОНЛ-РУС',
  rusOnline7: '7-ОНЛ-РУС',
  rusOnline8: '8-ОНЛ-РУС',
  rusOnline9: '9-ОНЛ-РУС',
  rusOnline10: '10-ОНЛ-РУС',
  rusOnline11: '11-ОНЛ-РУС',
  rusOnlineStudents: 'C-ОНЛ-РУС',
  rusOnlineOther: 'O-ОНЛ-РУС',
  rusOnlineExternal: 'Э-ОНЛ-РУС',
  rusOnlineSchool8: '8Ш-ОНЛ-РУС',
  rusOnlineSchool9: '9Ш-ОНЛ-РУС',
  rusOnlineSchool10: '10Ш-ОНЛ-РУС',
  rusOnlineSchool11: '11Ш-ОНЛ-РУС',
  rusOnlinePract11: '11П-ОНЛ-РУС',
  socOnline1: '1-ОНЛ-ОБЩ',
  socOnline2: '2-ОНЛ-ОБЩ',
  socOnline3: '3-ОНЛ-ОБЩ',
  socOnline4: '4-ОНЛ-ОБЩ',
  socOnline5: '5-ОНЛ-ОБЩ',
  socOnline6: '6-ОНЛ-ОБЩ',
  socOnline7: '7-ОНЛ-ОБЩ',
  socOnline8: '8-ОНЛ-ОБЩ',
  socOnline9: '9-ОНЛ-ОБЩ',
  socOnline10: '10-ОНЛ-ОБЩ',
  socOnline11: '11-ОНЛ-ОБЩ',
  socOnlineStudents: 'C-ОНЛ-ОБЩ',
  socOnlineOther: 'O-ОНЛ-ОБЩ',
  socOnlineExternal: 'Э-ОНЛ-ОБЩ',
  socOnlineSchool8: '8Ш-ОНЛ-ОБЩ',
  socOnlineSchool9: '9Ш-ОНЛ-ОБЩ',
  socOnlineSchool10: '10Ш-ОНЛ-ОБЩ',
  socOnlineSchool11: '11Ш-ОНЛ-ОБЩ',
  socOnlinePract11: '11П-ОНЛ-ОБЩ',
  mathPracticum1: '1-МАТ-ПРАКТ',
  mathPracticum2: '2-МАТ-ПРАКТ',
  mathPracticum3: '3-МАТ-ПРАКТ',
  mathPracticum4: '4-МАТ-ПРАКТ',
  mathPracticum5: '5-МАТ-ПРАКТ',
  mathPracticum6: '6-МАТ-ПРАКТ',
  mathPracticum7: '7-МАТ-ПРАКТ',
  mathPracticum8: '8-МАТ-ПРАКТ',
  mathPracticum9: '9-МАТ-ПРАКТ',
  mathPracticum10: '10-МАТ-ПРАКТ',
  mathPracticum11: '11-МАТ-ПРАКТ',
  mathPracticumStudents: 'C-МАТ-ПРАКТ',
  mathPracticumOther: 'O-МАТ-ПРАКТ',
  mathPracticumExternal: 'Э-МАТ-ПРАКТ',
  mathPracticumSchool8: '8Ш-МАТ-ПРАКТ',
  mathPracticumSchool9: '9Ш-МАТ-ПРАКТ',
  mathPracticumSchool10: '10Ш-МАТ-ПРАКТ',
  mathPracticumSchool11: '11Ш-МАТ-ПРАКТ',
  mathPracticumPract11: '11П-МАТ-ПРАКТ',
  socPracticum1: '1-ОБЩ-ПРАКТ',
  socPracticum2: '2-ОБЩ-ПРАКТ',
  socPracticum3: '3-ОБЩ-ПРАКТ',
  socPracticum4: '4-ОБЩ-ПРАКТ',
  socPracticum5: '5-ОБЩ-ПРАКТ',
  socPracticum6: '6-ОБЩ-ПРАКТ',
  socPracticum7: '7-ОБЩ-ПРАКТ',
  socPracticum8: '8-ОБЩ-ПРАКТ',
  socPracticum9: '9-ОБЩ-ПРАКТ',
  socPracticum10: '10-ОБЩ-ПРАКТ',
  socPracticum11: '11-ОБЩ-ПРАКТ',
  socPracticumStudents: 'C-ОБЩ-ПРАКТ',
  socPracticumOther: 'O-ОБЩ-ПРАКТ',
  socPracticumExternal: 'Э-ОБЩ-ПРАКТ',
  socPracticumSchool8: '8Ш-ОБЩ-ПРАКТ',
  socPracticumSchool9: '9Ш-ОБЩ-ПРАКТ',
  socPracticumSchool10: '10Ш-ОБЩ-ПРАКТ',
  socPracticumSchool11: '11Ш-ОБЩ-ПРАКТ',
  socPracticumPract11: '11П-ОБЩ-ПРАКТ',
  physPracticum1: '1-ФИЗ-ПРАКТ',
  physPracticum2: '2-ФИЗ-ПРАКТ',
  physPracticum3: '3-ФИЗ-ПРАКТ',
  physPracticum4: '4-ФИЗ-ПРАКТ',
  physPracticum5: '5-ФИЗ-ПРАКТ',
  physPracticum6: '6-ФИЗ-ПРАКТ',
  physPracticum7: '7-ФИЗ-ПРАКТ',
  physPracticum8: '8-ФИЗ-ПРАКТ',
  physPracticum9: '9-ФИЗ-ПРАКТ',
  physPracticum10: '10-ФИЗ-ПРАКТ',
  physPracticum11: '11-ФИЗ-ПРАКТ',
  physPracticumStudents: 'C-ФИЗ-ПРАКТ',
  physPracticumOther: 'O-ФИЗ-ПРАКТ',
  physPracticumExternal: 'Э-ФИЗ-ПРАКТ',
  physPracticumSchool8: '8Ш-ФИЗ-ПРАКТ',
  physPracticumSchool9: '9Ш-ФИЗ-ПРАКТ',
  physPracticumSchool10: '10Ш-ФИЗ-ПРАКТ',
  physPracticumSchool11: '11Ш-ФИЗ-ПРАКТ',
  physPracticumPract11: '11П-ФИЗ-ПРАКТ',
  chemPracticum1: '1-ХИМ-ПРАКТ',
  chemPracticum2: '2-ХИМ-ПРАКТ',
  chemPracticum3: '3-ХИМ-ПРАКТ',
  chemPracticum4: '4-ХИМ-ПРАКТ',
  chemPracticum5: '5-ХИМ-ПРАКТ',
  chemPracticum6: '6-ХИМ-ПРАКТ',
  chemPracticum7: '7-ХИМ-ПРАКТ',
  chemPracticum8: '8-ХИМ-ПРАКТ',
  chemPracticum9: '9-ХИМ-ПРАКТ',
  chemPracticum10: '10-ХИМ-ПРАКТ',
  chemPracticum11: '11-ХИМ-ПРАКТ',
  chemPracticumStudents: 'C-ХИМ-ПРАКТ',
  chemPracticumOther: 'O-ХИМ-ПРАКТ',
  chemPracticumExternal: 'Э-ХИМ-ПРАКТ',
  chemPracticumSchool8: '8Ш-ХИМ-ПРАКТ',
  chemPracticumSchool9: '9Ш-ХИМ-ПРАКТ',
  chemPracticumSchool10: '10Ш-ХИМ-ПРАКТ',
  chemPracticumSchool11: '11Ш-ХИМ-ПРАКТ',
  chemPracticumPract11: '11П-ХИМ-ПРАКТ',
  bioPracticum1: '1-БИО-ПРАКТ',
  bioPracticum2: '2-БИО-ПРАКТ',
  bioPracticum3: '3-БИО-ПРАКТ',
  bioPracticum4: '4-БИО-ПРАКТ',
  bioPracticum5: '5-БИО-ПРАКТ',
  bioPracticum6: '6-БИО-ПРАКТ',
  bioPracticum7: '7-БИО-ПРАКТ',
  bioPracticum8: '8-БИО-ПРАКТ',
  bioPracticum9: '9-БИО-ПРАКТ',
  bioPracticum10: '10-БИО-ПРАКТ',
  bioPracticum11: '11-БИО-ПРАКТ',
  bioPracticumStudents: 'C-БИО-ПРАКТ',
  bioPracticumOther: 'O-БИО-ПРАКТ',
  bioPracticumExternal: 'Э-БИО-ПРАКТ',
  bioPracticumSchool8: '8Ш-БИО-ПРАКТ',
  bioPracticumSchool9: '9Ш-БИО-ПРАКТ',
  bioPracticumSchool10: '10Ш-БИО-ПРАКТ',
  bioPracticumSchool11: '11Ш-БИО-ПРАКТ',
  bioPracticumPract11: '11П-БИО-ПРАКТ',
  infPracticum1: '1-ИНФ-ПРАКТ',
  infPracticum2: '2-ИНФ-ПРАКТ',
  infPracticum3: '3-ИНФ-ПРАКТ',
  infPracticum4: '4-ИНФ-ПРАКТ',
  infPracticum5: '5-ИНФ-ПРАКТ',
  infPracticum6: '6-ИНФ-ПРАКТ',
  infPracticum7: '7-ИНФ-ПРАКТ',
  infPracticum8: '8-ИНФ-ПРАКТ',
  infPracticum9: '9-ИНФ-ПРАКТ',
  infPracticum10: '10-ИНФ-ПРАКТ',
  infPracticum11: '11-ИНФ-ПРАКТ',
  infPracticumStudents: 'C-ИНФ-ПРАКТ',
  infPracticumOther: 'O-ИНФ-ПРАКТ',
  infPracticumExternal: 'Э-ИНФ-ПРАКТ',
  infPracticumSchool8: '8Ш-ИНФ-ПРАКТ',
  infPracticumSchool9: '9Ш-ИНФ-ПРАКТ',
  infPracticumSchool10: '10Ш-ИНФ-ПРАКТ',
  infPracticumSchool11: '11Ш-ИНФ-ПРАКТ',
  infPracticumPract11: '11П-ИНФ-ПРАКТ',
  rusPracticum1: '1-РУС-ПРАКТ',
  rusPracticum2: '2-РУС-ПРАКТ',
  rusPracticum3: '3-РУС-ПРАКТ',
  rusPracticum4: '4-РУС-ПРАКТ',
  rusPracticum5: '5-РУС-ПРАКТ',
  rusPracticum6: '6-РУС-ПРАКТ',
  rusPracticum7: '7-РУС-ПРАКТ',
  rusPracticum8: '8-РУС-ПРАКТ',
  rusPracticum9: '9-РУС-ПРАКТ',
  rusPracticum10: '10-РУС-ПРАКТ',
  rusPracticum11: '11-РУС-ПРАКТ',
  rusPracticumStudents: 'C-РУС-ПРАКТ',
  rusPracticumOther: 'O-РУС-ПРАКТ',
  rusPracticumExternal: 'Э-РУС-ПРАКТ',
  rusPracticumSchool8: '8Ш-РУС-ПРАКТ',
  rusPracticumSchool9: '9Ш-РУС-ПРАКТ',
  rusPracticumSchool10: '10Ш-РУС-ПРАКТ',
  rusPracticumSchool11: '11Ш-РУС-ПРАКТ',
  rusPracticumPract11: '11П-РУС-ПРАКТ',
  hisPracticum1: '1-ИСТ-ПРАКТ',
  hisPracticum2: '2-ИСТ-ПРАКТ',
  hisPracticum3: '3-ИСТ-ПРАКТ',
  hisPracticum4: '4-ИСТ-ПРАКТ',
  hisPracticum5: '5-ИСТ-ПРАКТ',
  hisPracticum6: '6-ИСТ-ПРАКТ',
  hisPracticum7: '7-ИСТ-ПРАКТ',
  hisPracticum8: '8-ИСТ-ПРАКТ',
  hisPracticum9: '9-ИСТ-ПРАКТ',
  hisPracticum10: '10-ИСТ-ПРАКТ',
  hisPracticum11: '11-ИСТ-ПРАКТ',
  hisPracticumStudents: 'C-ИСТ-ПРАКТ',
  hisPracticumOther: 'O-ИСТ-ПРАКТ',
  hisPracticumExternal: 'Э-ИСТ-ПРАКТ',
  hisPracticumSchool8: '8Ш-ИСТ-ПРАКТ',
  hisPracticumSchool9: '9Ш-ИСТ-ПРАКТ',
  hisPracticumSchool10: '10Ш-ИСТ-ПРАКТ',
  hisPracticumSchool11: '11Ш-ИСТ-ПРАКТ',
  hisPracticumPract11: '11П-ИСТ-ПРАКТ',
  engPracticum1: '1-АНГ-ПРАКТ',
  engPracticum2: '2-АНГ-ПРАКТ',
  engPracticum3: '3-АНГ-ПРАКТ',
  engPracticum4: '4-АНГ-ПРАКТ',
  engPracticum5: '5-АНГ-ПРАКТ',
  engPracticum6: '6-АНГ-ПРАКТ',
  engPracticum7: '7-АНГ-ПРАКТ',
  engPracticum8: '8-АНГ-ПРАКТ',
  engPracticum9: '9-АНГ-ПРАКТ',
  engPracticum10: '10-АНГ-ПРАКТ',
  engPracticum11: '11-АНГ-ПРАКТ',
  engPracticumStudents: 'C-АНГ-ПРАКТ',
  engPracticumOther: 'O-АНГ-ПРАКТ',
  engPracticumExternal: 'Э-АНГ-ПРАКТ',
  engPracticumSchool8: '8Ш-АНГ-ПРАКТ',
  engPracticumSchool9: '9Ш-АНГ-ПРАКТ',
  engPracticumSchool10: '10Ш-АНГ-ПРАКТ',
  engPracticumSchool11: '11Ш-АНГ-ПРАКТ',
  engPracticumPract11: '11П-АНГ-ПРАКТ',
  geoPracticum1: '1-ГЕО-ПРАКТ',
  geoPracticum2: '2-ГЕО-ПРАКТ',
  geoPracticum3: '3-ГЕО-ПРАКТ',
  geoPracticum4: '4-ГЕО-ПРАКТ',
  geoPracticum5: '5-ГЕО-ПРАКТ',
  geoPracticum6: '6-ГЕО-ПРАКТ',
  geoPracticum7: '7-ГЕО-ПРАКТ',
  geoPracticum8: '8-ГЕО-ПРАКТ',
  geoPracticum9: '9-ГЕО-ПРАКТ',
  geoPracticum10: '10-ГЕО-ПРАКТ',
  geoPracticum11: '11-ГЕО-ПРАКТ',
  geoPracticumStudents: 'C-ГЕО-ПРАКТ',
  geoPracticumOther: 'O-ГЕО-ПРАКТ',
  geoPracticumExternal: 'Э-ГЕО-ПРАКТ',
  geoPracticumSchool8: '8Ш-ГЕО-ПРАКТ',
  geoPracticumSchool9: '9Ш-ГЕО-ПРАКТ',
  geoPracticumSchool10: '10Ш-ГЕО-ПРАКТ',
  geoPracticumSchool11: '11Ш-ГЕО-ПРАКТ',
  geoPracticumPract11: '11П-ГЕО-ПРАКТ',
  izl1: '1-ИЗЛ',
  izl2: '2-ИЗЛ',
  izl3: '3-ИЗЛ',
  izl4: '4-ИЗЛ',
  izl5: '5-ИЗЛ',
  izl6: '6-ИЗЛ',
  izl7: '7-ИЗЛ',
  izl8: '8-ИЗЛ',
  izl9: '9-ИЗЛ',
  izl10: '10-ИЗЛ',
  izl11: '11-ИЗЛ',
  izlStudents: 'C-ИЗЛ',
  izlOther: 'O-ИЗЛ',
  izlExternal: 'Э-ИЗЛ',
  izlSchool8: '8Ш-ИЗЛ',
  izlSchool9: '9Ш-ИЗЛ',
  izlSchool10: '10Ш-ИЗЛ',
  izlSchool11: '11Ш-ИЗЛ',
  izlPract11: '11П-ИЗЛ',
  geoOge1: '1-ГЕО-OГЭ',
  geoOge2: '2-ГЕО-OГЭ',
  geoOge3: '3-ГЕО-OГЭ',
  geoOge4: '4-ГЕО-OГЭ',
  geoOge5: '5-ГЕО-OГЭ',
  geoOge6: '6-ГЕО-OГЭ',
  geoOge7: '7-ГЕО-OГЭ',
  geoOge8: '8-ГЕО-OГЭ',
  geoOge9: '9-ГЕО-OГЭ',
  geoOge10: '10-ГЕО-OГЭ',
  geoOge11: '11-ГЕО-OГЭ',
  geoOgeStudents: 'C-ГЕО-OГЭ',
  geoOgeOther: 'O-ГЕО-OГЭ',
  geoOgeExternal: 'Э-ГЕО-OГЭ',
  geoOgeSchool8: '8Ш-ГЕО-OГЭ',
  geoOgeSchool9: '9Ш-ГЕО-OГЭ',
  geoOgeSchool10: '10Ш-ГЕО-OГЭ',
  geoOgeSchool11: '11Ш-ГЕО-OГЭ',
  geoOgePract11: '11П-ГЕО-OГЭ',
  engSpoken1: '1-АНГ-Р',
  engSpoken2: '2-АНГ-Р',
  engSpoken3: '3-АНГ-Р',
  engSpoken4: '4-АНГ-Р',
  engSpoken5: '5-АНГ-Р',
  engSpoken6: '6-АНГ-Р',
  engSpoken7: '7-АНГ-Р',
  engSpoken8: '8-АНГ-Р',
  engSpoken9: '9-АНГ-Р',
  engSpoken10: '10-АНГ-Р',
  engSpoken11: '11-АНГ-Р',
  engSpokenStudents: 'C-АНГ-Р',
  engSpokenOther: 'O-АНГ-Р',
  engSpokenExternal: 'Э-АНГ-Р',
  engSpokenSchool8: '8Ш-АНГ-Р',
  engSpokenSchool9: '9Ш-АНГ-Р',
  engSpokenSchool10: '10Ш-АНГ-Р',
  engSpokenSchool11: '11Ш-АНГ-Р',
  engSpokenPract11: '11П-АНГ-Р',
} as const

export const BranchLabel = {
  ohr: 'ОХР',
  pvn: 'ВЕР',
  bgt: 'БАГ',
  izm: 'ИЗМ',
  opl: 'ОКТ',
  rpt: 'РЯЗ',
  skl: 'СКЛ',
  orh: 'ОРЕ',
  ann: 'АНН',
  per: 'ПЕР',
  klg: 'КЛЖ',
  brt: 'БРА',
  str: 'СТР',
  vld: 'ВЛА',
  bel: 'БЕЛ',
  bib: 'БИБ',
  svi: 'СВИ',
  nag: 'НАГ',
  sok: 'СОК',
  pla: 'ПЛА',
  vod: 'ВОД',
  trg: 'ТУР',
} as const

export const RequestStatusLabel = {
  new: 'новые',
  awaiting: 'в ожидании',
  finished: 'выполненные',
  trash: 'архив',
} as const

export const WeekdayLabel = {
  0: 'пн',
  1: 'вт',
  2: 'ср',
  3: 'чт',
  4: 'пт',
  5: 'сб',
  6: 'вс',
} as const

export const LessonStatusLabel = {
  planned: 'планируется',
  conducted: 'проведено',
  cancelled: 'отменено',
} as const

export const ClientLessonStatusLabel = {
  present: 'был',
  late: 'опоздал',
  absent: 'не был',
} as const

export const QuarterLabel = {
  q1: '1 четверть',
  q2: '2 четверть',
  q3: '3 четверть',
  q4: '4 четверть',
  final: 'итоговая',
} as const

export const MonthLabel = {
  1: 'январь',
  2: 'февраль',
  3: 'март',
  4: 'апрель',
  5: 'май',
  6: 'июнь',
  7: 'июль',
  8: 'август',
  9: 'сентябрь',
  10: 'октябрь',
  11: 'ноябрь',
  12: 'декабрь',
} as const

export const MonthLabelShort = {
  1: 'янв',
  2: 'фев',
  3: 'мар',
  4: 'апр',
  5: 'мая',
  6: 'июн',
  7: 'июл',
  8: 'авг',
  9: 'сен',
  10: 'окт',
  11: 'ноя',
  12: 'дек',
} as const

// export const MonthLabelDative = [
//   'января',
//   'февраля',
//   'марта',
//   'апреля',
//   'мая',
//   'июня',
//   'июля',
//   'августа',
//   'сентября',
//   'октября',
//   'ноября',
//   'декабря',
// ] as const

export const EntityTypeValue = {
  request: 'App\\Models\\Request',
  client: 'App\\Models\\Client',
  clientParent: 'App\\Models\\ClientParent',
  contract: 'App\\Models\\Contract',
  teacher: 'App\\Models\\Teacher',
  user: 'App\\Models\\User',
  group: 'App\\Models\\Group',
} as const

export const EntityTypeLabel = {
  'App\\Models\\Request': 'заявка',
  'App\\Models\\Client': 'клиент',
  'App\\Models\\ClientParent': 'родитель',
  'App\\Models\\Contract': 'договор',
  'App\\Models\\Teacher': 'преподаватель',
  'App\\Models\\User': 'администратор',
  'App\\Models\\Group': 'группа',
} as const

export const LessonScoreLabel = {
  5: 'пять',
  4: 'четыре',
  3: 'три',
  2: 'два',
}

export const YearLabel = {
  2024: '2024–2025 уч. г.',
  2023: '2023–2024 уч. г.',
  2022: '2022–2023 уч. г.',
  2021: '2021–2022 уч. г.',
  2020: '2020–2021 уч. г.',
  2019: '2019–2020 уч. г.',
  2018: '2018–2019 уч. г.',
  2017: '2017–2018 уч. г.',
  2016: '2016–2017 уч. г.',
  2015: '2015–2016 уч. г.',
} as const

/* eslint-disable */
export const CabinetLabel = {
  cab428: "К-428",
  cab430: "К-430",
  cab432: "К-432",
  cab433: "К-433",
  cab434: "К-434",
  cab439: "К-439",
  cab407: "К-407",
  cab409: "К-409",
  cab412: "К-412",
  cab413: "К-413",
  cab414: "К-414",
  cab417: "К-417",
  cab418: "К-418",
  cab420: "К-420",
  cab422: "К-422",
  cab423: "К-423",
  cab424: "К-424",
  cab310: "К-310",
  cab312: "К-312",
  cab314: "К-314",
  cab316: "К-316",
  tur10: "ТУР-10",
  tur35: "ТУР-35",
  tur205: "ТУР-205",
  tur214: "ТУР-214",
  tur221: "ТУР-221",
  tur301: "ТУР-301",
  tur302: "ТУР-302",
  tur303: "ТУР-303",
  tur304: "ТУР-304",
  tur305: "ТУР-305",
  tur310: "ТУР-310",
  tur311: "ТУР-311",
  tur314: "ТУР-314",
  tur319: "ТУР-319",
  tur320: "ТУР-320",
  tur321: "ТУР-321",
  tur322: "ТУР-322",
  tur507: "ТУР-507",
  tur809: "ТУР-809"
} as const;
/* eslint-enable */

export const TeacherStatusLabel = {
  inactive: 'неактивен',
  active: 'ведет занятия сейчас',
  earlyReserve: 'ранний запас',
  lateReserve: 'поздний запас',
  usedToWork: 'ранее работал',
  interview: 'собеседование',
  closed: 'закрыт',
} as const

export const UserStatusLabel: { [key: number]: string } = {
  1: 'действующий сотрудник',
  0: 'больше не работает',
}

export const SubjectLabel = {
  math: 'математика',
  phys: 'физика',
  chem: 'химия',
  bio: 'биология',
  inf: 'информатика',
  rus: 'русский язык',
  lit: 'литература',
  soc: 'обществознание',
  his: 'история',
  eng: 'английский язык',
  geo: 'география',
  soch: 'сочинение',
} as const

export const SubjectLabelShort = {
  math: 'МАТ',
  phys: 'ФИЗ',
  chem: 'ХИМ',
  bio: 'БИО',
  inf: 'ИНФ',
  rus: 'РУС',
  lit: 'ЛИТ',
  soc: 'ОБЩ',
  his: 'ИСТ',
  eng: 'АНГ',
  geo: 'ГЕО',
  soch: 'СОЧ',
} as const

export const TeacherPaymentMethodLabel = {
  card: 'карта',
  cash: 'наличные',
  invoice: 'счёт',
  mutual: 'взаимозачёт',
} as const

export const ContractPaymentMethodLabel = {
  card: 'карта',
  online: 'карта онлайн',
  cash: 'наличные',
  invoice: 'счёт',
} as const

export const ClientPaymentMethodLabel = {
  card: 'карта',
  cash: 'наличные',
} as const

export const CompanyLabel = {
  ooo: 'ООО',
  ip: 'ИП',
} as const

export const ExamLabel = {
  ogeMath: 'ОГЭ математика',
  ogePhys: 'ОГЭ физика',
  ogeChem: 'ОГЭ химия',
  ogeEng: 'ОГЭ английский',
  ogeInf: 'ОГЭ информатика',
  ogeRus: 'ОГЭ русский',
  ogeLit: 'ОГЭ литература',
  ogeGeo: 'ОГЭ география',
  ogeHis: 'ОГЭ история',
  ogeSoc: 'ОГЭ обществознание',
  egeMathBase: 'ЕГЭ математика база',
  egeMathProf: 'ЕГЭ математика профиль',
  egePhys: 'ЕГЭ физика',
  egeChem: 'ЕГЭ химия',
  egeEng: 'ЕГЭ английский',
  egeInf: 'ЕГЭ информатика',
  egeRus: 'ЕГЭ русский',
  egeLit: 'ЕГЭ литература',
  egeGeo: 'ЕГЭ география',
  egeHis: 'ЕГЭ история',
  egeSoc: 'ЕГЭ обществознание',
}

export const StatsModeLabel = {
  day: 'по дням',
  month: 'по месяцам',
  year: 'по годам',
} as const

export const LogTypeLabel = {
  create: 'создание',
  update: 'обновление',
  delete: 'удаление',
  view: 'просмотр',
  auth: 'авторизация',
} as const

export const LogTableLabel = {
  client_payments: 'client_payments',
  client_reviews: 'client_reviews',
  client_tests: 'client_tests',
  comments: 'comments',
  client_lessons: 'client_lessons',
  contract_version_payments: 'contract_version_payments',
  contract_version_programs: 'contract_version_programs',
  contract_versions: 'contract_versions',
  contracts: 'contracts',
  event_participants: 'event_participants',
  events: 'events',
  grades: 'grades',
  groups: 'groups',
  lessons: 'lessons',
  reports: 'reports',
  telegram_messages: 'telegram_messages',
  tests: 'tests',
  vacations: 'vacations',
} as const

export const ClientTestStatusLabel = {
  new: 'не пройден',
  active: 'активен',
  finished: 'завершен',
} as const

export const CallAppStatusFilterLabel = {
  all: 'все звонки',
  missed: 'пропущенные',
  active: 'активные',
  outgoing: 'исходящие',
} as const

export const SwampFilterStatusLabel = {
  toFulfil: 'к исполнению',
  exceedNoGroup: 'избыток по услугам + не в группе',
  completeNoGroup: 'исполнено + не в группе',
  inProcess: 'исполняется',
  exceedInGroup: 'избыток по услугам + в группе',
  completeInGroup: 'исполнено + в группе',
} as const

export const SendToLabel = {
  studentsAndParents: 'ученикам и родителям',
  students: 'только ученикам',
  parents: 'только родителям',
} as const

export const EventParticipantConfirmationLabel = {
  pending: 'не подтвердил участие',
  confirmed: 'подтвердил участие',
  rejected: 'отказался от участия',
} as const

export const TelegramListStatusLabel = {
  scheduled: 'запланировано',
  sending: 'отправляется',
  sent: 'отправлено',
} as const

export const ErrorCodeLabel = [1000] as const

export const PassTypeLabel = {
  person: 'на человека',
  car: 'на машину',
} as const

export const PassStatusLabel = {
  active: 'не использован',
  used: 'использован',
  expired: 'истёк',
} as const

export const RequestDirectionLabel = {
  courses9: 'курсы-9',
  courses10: 'курсы-10',
  courses11: 'курсы-11',
  school8: 'школа-8',
  school9: 'школа-9',
  school10: 'школа-10',
  school11: 'школа-11',
  external: 'экстернат',
  practicum: 'практикум',
  egeTrial: 'пробный ЕГЭ',
  python: 'python',
  english: 'английский',
  online: 'онлайн',
} as const
