import type { CompanyType } from './models'

export const GRADE: Record<string, string> = {
  grade1: '1 класс',
  grade2: '2 класс',
  grade3: '3 класс',
  grade4: '4 класс',
  grade5: '5 класс',
  grade6: '6 класс',
  grade7: '7 класс',
  grade8: '8 класс',
  grade9: '9 класс',
  grade10: '10 класс',
  grade11: '11 класс',
  students: 'студенты',
  other: 'другие',
  external: 'экстернат',
  school8: 'школа 8 класс',
  school9: 'школа 9 класс',
  school10: 'школа 10 класс',
  online: 'онлайн',
  practicum11: 'практикум',
}

export const SUBJECT: Record<string, string> = {
  math: 'математика',
  phys: 'физика',
  chem: 'химимя',
  bio: 'биология',
  inf: 'информатика',
  rus: 'русский язык',
  lit: 'литература',
  soc: 'обществознание',
  his: 'история',
  eng: 'английский язык',
  geo: 'география',
  soch: 'сочинение',
}

export const SUBJECT_SHORT: Record<string, string> = {
  math: 'МАТ',
  phys: 'ФИЗ',
  chem: 'ХИМ',
  bio: 'БИО',
  inf: 'ИНФ',
  rus: 'РУС',
  lit: 'ЛИТ',
  soc: 'ОБЩ',
  his: 'ИСТ',
  eng: 'АНГ',
  geo: 'ГЕО',
  soch: 'СОЧ',
}

export const BRANCHES: Record<string, string> = {
  ohr: 'ОХР',
  pvn: 'ВЕР',
  bgt: 'БАГ',
  izm: 'ИЗМ',
  opl: 'ОКТ',
  rpt: 'РЯЗ',
  skl: 'СКЛ',
  orh: 'ОРЕ',
  ann: 'АНН',
  per: 'ПЕР',
  klg: 'КЛЖ',
  brt: 'БРА',
  str: 'СТР',
  vld: 'ВЛА',
  bel: 'БЕЛ',
  bib: 'БИБ',
  svi: 'СВИ',
  nag: 'НАГ',
  sok: 'СОК',
  pla: 'ПЛА',
  vod: 'ВОД',
  trg: 'ТУР',
} as const

export const PROGRAM: Record<Program, string> = {
  math9: 'математика 9 класс',
  phys9: 'физика 9 класс',
  chem9: 'химия 9 класс',
  bio9: 'биология 9 класс',
  inf9: 'информатика 9 класс',
  rus9: 'русский 9 класс',
  lit9: 'литература 9 класс',
  soc9: 'обществознание 9 класс',
  his9: 'история 9 класс',
  eng9: 'английский 9 класс',
  geo9: 'география 9 класс',
  essay9: 'итоговое сочинение',

  math10: 'математика 9 класс',
  phys10: 'физика 9 класс',
  chem10: 'химия 10 класс',
  bio10: 'биология 10 класс',
  inf10: 'информатика 10 класс',
  rus10: 'русский язык 10 класс',
  lit10: 'литература 10 класс',
  soc10: 'обществознание 10 класс',
  his10: 'история 10 класс',
  eng10: 'английский язык 10 класс',

  math11: 'математика 11 класс',
  phys11: 'физика 11 класс',
  chem11: 'химия 11 класс',
  bio11: 'биология 11 класс',
  inf11: 'информатика 11 класс',
  rus11: 'русский язык 11 класс',
  lit11: 'литература 11 класс',
  soc11: 'обществознанеие 11 класс',
  his11: 'история 11 класс',
  eng11: 'английский язык 11 класс',
  geo11: 'география 11 класс',
  essay11: 'итоговое собеседование',

  mathExt: 'математика экстернат',
  physExt: 'физика экстернат',
  chemExt: 'химия экстернат',
  bioExt: 'биология экстернат',
  infExt: 'информатика экстернат',
  rusExt: 'русский язык экстернат',
  litExt: 'литература экстернат',
  socExt: 'обществознание экстернат',
  hisExt: 'история экстетрнат',
  engExt: 'английский язык экстернат',
  geoExt: 'география экстернат',

  mathSchool8: 'математика школа 8 класс',
  physSchool8: 'физика школа 8 класс',
  chemSchool8: 'химия школа 8 класс',
  bioSchool8: 'биология школа 8 класс',
  infSchool8: 'информатика школа 8 класс',
  rusSchool8: 'русский язык школа 8 класс',
  litSchool8: 'литература школа 8 класс',
  socSchool8: 'обществознание школа 8 класс',
  hisSchool8: 'история школа 8 класс',
  engSchool8: 'английский язык школа 8 класс',
  geoSchool8: 'география школа 8 класс',

  mathSchool9: 'математика школа 9 класс',
  physSchool9: 'физика школа 9 класс',
  chemSchool9: 'химия школа 9 класс',
  bioSchool9: 'биология школа 9 класс',
  infSchool9: 'информатика школа 9 класс',
  rusSchool9: 'русский язык школа 9 класс',
  litSchool9: 'литература школа 9 класс',
  socSchool9: 'обществознание школа 9 класс',
  hisSchool9: 'история школа 9 класс',
  engSchool9: 'английский язык школа 9 класс',
  geoSchool9: 'география школа 9 класс',

  mathSchool10: 'математика школа 10 класс',
  physSchool10: 'физика школа 10 класс',
  chemSchool10: 'химия школа 10 класс',
  bioSchool10: 'биология школа 10 класс',
  infSchool10: 'информатика школа 10 класс',
  rusSchool10: 'русский язык школа 10 класс',
  litSchool10: 'литература школа 10 класс',
  socSchool10: 'обществознание школа 10 класс',
  hisSchool10: 'история школа 10 класс',
  engSchool10: 'английский язык школа 10 класс',
  geoSchool10: 'география школа 10 класс',

  physSchoolOge: 'физика школа ОГЭ',
  chemSchoolOge: 'химия школа ОГЭ',
  bioSchoolOge: 'биология школа ОГЭ',
  infSchoolOge: 'информатика школа ОГЭ',
  litSchoolOge: 'литература школа ОГЭ',
  socSchoolOge: 'обществознание школа ОГЭ',
  hisSchoolOge: 'история школа ОГЭ',
  engSchoolOge: 'английский язык школа ОГЭ',

  mathPracticum: 'математика практикум',
  physPracticum: 'физика практикум',
  chemPracticum: 'химия практикум',
  bioPracticum: 'биология практикум',
  infPracticum: 'информатика практикум',
  rusPracticum: 'русский язык практикум',
  socPracticum: 'обществознание практикум',
  hisPracticum: 'история практикум',
  engPracticum: 'английский язык практикум',
  geoPracticum: 'география практикум',

  mathBase: 'математика база',
  mathProf: 'математика профиль',
}

export const ENTITY_TYPE = {
  client: 'App\\Models\\Client',
  teacher: 'App\\Models\\Teacher',
  user: 'App\\Models\\User',
}

export const YEARS = [
  2024,
  2023,
  2022,
  2021,
  2020,
  2019,
  2018,
  2017,
  2016,
  2015,
] as const

export const COMPANY_TYPE: Record<CompanyType, string> = {
  ip: 'ИП',
  ooo: 'ООО',
}

export type Programs = Program[]
