<script setup lang="ts">
const { $addSseListener, $removeSseListener, $isTgMiniApp } = useNuxtApp()
const { public: config } = useRuntimeConfig()
const { rememberUser, logInAndRemember } = useAuthStore()
const magicLink = useMagicLink()
const number = ref('')
const phoneMask = { mask: '+7 (###) ###-##-##' }
const currentUser = ref<AuthResource>()
const currentPhone = ref<PhoneResource>()
const loading = ref(false)
const errors = ref<{
  number?: ResponseErrors
  code?: ResponseErrors
}>({})
const otpInput = ref()
const phoneInput = ref()
const otp = reactive({
  code: '',
  error: false,
  loading: false,
})

enum Step {
  EnterPhoneNumber,
  RememberUser,
  TelegramBotInstructions,
  VerifyCode,
  MagicLink,
}

const isCandidatesError = ref(false)

const tab = ref(
  magicLink.hasMagicLink
    ? Step.MagicLink
    : (rememberUser ? Step.RememberUser : Step.EnterPhoneNumber),
)

if (magicLink.hasMagicLink) {
  nextTick(magicLink.authViaMagicLink)
}

const authViaTelegram = ref(false)

// QR generated by https://mini-qr-code-generator.vercel.app/
const bot = config.env === 'local'
  ? { url: 'https://t.me/ec_local_bot', qr: '/img/qr-auth-local.png' }
  : {
      url: 'https://t.me/egecentr_bot',
      qr: '/img/qr-auth.png',
    }

async function onPhoneEnter() {
  loading.value = true
  errors.value = {}
  const { data, error } = await useHttp<{
    user: AuthResource
    phone: PhoneResource
  }>(
    `pub/auth/submit-phone`,
    {
      method: 'post',
      body: {
        number: number.value,
      },
    },
  )
  setTimeout(() => (loading.value = false), 300)
  if (error.value) {
    errors.value = error.value.data.errors
    if (error.value.data.message === 'кандидаты <> 1') {
      isCandidatesError.value = true
    }
    return
  }
  const { user, phone } = data.value!
  currentUser.value = user
  currentPhone.value = phone
  nextTick(() => {
    tab.value = (phone.telegram_id || phone.is_telegram_disabled)
      ? Step.VerifyCode
      : Step.TelegramBotInstructions
  })
}

function otherUser() {
  tab.value = Step.EnterPhoneNumber
  // setTimeout(() => (cookieUser.value = null), 1000)
}

function continueRememberUser() {
  if (rememberUser === undefined) {
    return
  }
  number.value = rememberUser.number
  onPhoneEnter()
}

function openBot() {
  window.open(bot.url, '_blank')
}

async function onOtpFinish() {
  errors.value = {}
  otp.loading = true
  const { data, error } = await useHttp<TokenResponse>(
    `pub/auth/verify-code`,
    {
      method: 'post',
      body: {
        phone_id: currentPhone.value?.id,
        code: otp.code,
      },
    },
  )
  if (error.value) {
    otp.loading = false
    otp.code = ''
    errors.value = error.value.data.errors
    nextTick(() => otpInput.value.focus())
    return
  }
  logInAndRemember(data.value!)
}

watch(tab, (newStep) => {
  console.log('newStep', newStep)
  switch (newStep) {
    case Step.EnterPhoneNumber:
      setTimeout(() => phoneInput.value.focus(), 300)
      break

    case Step.TelegramBotInstructions:
      $addSseListener('TelegramBotAdded', (u: AuthResource) => {
        if (currentUser.value?.id === u.id) {
          onPhoneEnter()
        }
      })
      break

    case Step.VerifyCode:
      setTimeout(() => otpInput.value.focus(), 300)
      break
  }
})

onUnmounted(() => $removeSseListener('TelegramBotAdded'))

nextTick(() => {
  if ($isTgMiniApp) {
    authViaTelegram.value = true
  }

  document.documentElement.classList.add('login-page')
})

definePageMeta({ layout: 'login' })
</script>

<template>
  <form class="login">
    <div class="login__logo">
      <img src="/img/logo.svg" />
    </div>
    <v-fade-transition>
      <div v-if="isCandidatesError" class="fullscreen-message">
        <p>
          Не получается войти в личный кабинет 😔
          <br />
          <br />
          Обратитесь, пожалуйста, в учебную часть, и мы всё исправим.

          <v-btn color="primary" block size="x-large" @click="isCandidatesError = false">
            назад
          </v-btn>
        </p>
      </div>
    </v-fade-transition>
    <TgMiniAppAuth v-if="authViaTelegram" />
    <v-window v-else v-model="tab" :touch="false">
      <v-window-item>
        <v-text-field
          ref="phoneInput"
          v-model="number"
          v-maska="phoneMask"
          label="Телефон"
          type="tel"
          :error-messages="errors.number"
          @keydown.enter="onPhoneEnter()"
        />
        <v-btn color="primary" :loading="loading" block size="x-large" @click="onPhoneEnter()">
          Войти
        </v-btn>
      </v-window-item>

      <v-window-item eager>
        <v-card v-if="rememberUser" variant="tonal">
          <template #title>
            {{ formatName(rememberUser) }}
          </template>
          <template #subtitle>
            {{ formatPhone(rememberUser.number) }}
          </template>
          <template #prepend>
            <UiAvatar :item="rememberUser" :size="63" class="mr-3" />
          </template>
        </v-card>
        <v-btn
          color="primary"
          :loading="loading"
          block
          size="x-large"
          @click="continueRememberUser()"
        >
          продолжить
        </v-btn>
        <div class="login__other">
          <span @click="otherUser()"> другой пользователь </span>
        </div>
      </v-window-item>

      <v-window-item eager>
        <div v-if="currentUser" class="login__info">
          <div class="login__info-title">
            {{ currentUser.first_name }}, здравствуйте!
          </div>
          <div class="login__info-tg">
            Это ваш первый вход в Личный Кабинет. Для продолжения нужно добавить бота Telegram.
            <div class="login__info-tg-steps">
              <div>
                <img src="/img/1.svg" alt="" />
                Убедитесь, что на вашем телефоне установлен Telegram
              </div>
              <div>
                <img src="/img/2.svg" alt="" />
                Перейдите в бота по кнопке ниже и нажмите «Начать»
              </div>
            </div>
          </div>
          <v-btn color="primary" block size="x-large" @click="openBot()">
            Перейти в бота
          </v-btn>
        </div>
      </v-window-item>

      <v-window-item eager>
        <div class="login__info">
          <div class="login__info-title">
            Проверьте {{ currentPhone?.telegram_id ? 'Telegram' : 'СМС' }}
          </div>
          <div v-if="!!errors.code" class="text-error">
            Введённый код неверный<br />
            Попробуйте ещё раз
          </div>
          <div v-else>
            Введите код, который пришёл к вам в сообщения
          </div>
        </div>
        <v-otp-input
          ref="otpInput"
          v-model="otp.code"
          :disabled="otp.loading"
          :error="!!errors.code"
          :length="4"
          class="mt-5"
          width="240"
          @finish="onOtpFinish"
        />
      </v-window-item>

      <!-- reverse transition fix -->
      <v-window-item>
        <div class="login__info-title text-center mt-12 mb-12">
          Вход в личный кабинет...
        </div>
        <div class="login__magic-link">
          <div v-if="magicLink.hasError.value" class="text-error text-center">
            <div class="mb-6">
              <v-icon icon="$error" :size="50"></v-icon>
            </div>
            Не получилось войти <br />
            Обратитесь в администрацию
          </div>
          <div v-else class="text-center">
            <v-progress-circular :size="50" indeterminate />
          </div>
        </div>
      </v-window-item>
    </v-window>
  </form>
</template>

<style lang="scss">
.login {
  z-index: 2;
  width: 100%;

  &-page {
    overflow: hidden !important;
  }

  & > .v-text-field {
    margin-bottom: 20px;
    // .v-field__outline {
    //   color: rgb(var(--v-theme-primary));
    //   label {
    //     color: rgba(
    //       var(--v-theme-on-background),
    //       var(--v-high-emphasis-opacity)
    //     ) !important;
    //   }
    // }
  }

  button {
    margin-top: 60px;
  }

  &__logo {
    text-align: center;
    padding: 40px 0 30px;

    img {
      width: 70px;
    }
  }

  &__qr {
    margin-top: 40px;
    text-align: center;

    img {
      width: 150px;
    }
  }

  &__info {
    text-align: center;
    text-wrap: balance;

    &-title {
      font-size: 20px;
      font-weight: bold;
      margin-bottom: 20px;
    }

    &-tg {
      //font-size: 16px;
      &-steps {
        text-align: left;
        display: flex;
        gap: 20px;
        flex-direction: column;
        width: 80%;
        margin: 20px auto 0;

        & > div {
          display: flex;
          align-items: center;
          line-height: 20px;

          img {
            height: 30px;
            margin-right: 20px;
          }
        }
      }
    }
  }

  &__other {
    text-align: center;
    position: relative;
    width: 100%;
    top: 14px;
    span {
      cursor: pointer;
      color: rgb(var(--v-theme-gray));
      transition: color cubic-bezier(0.4, 0, 0.2, 1) 0.15s;
      &:hover {
        color: black;
      }
    }
  }

  .v-card-item {
    padding-left: 0 !important;
  }

  .v-btn__underlay {
    border-radius: 50px !important;
  }

  .v-card__underlay {
    // background: rgb(var(--v-theme-gray)) !important;
    background: none !important;
    // opacity: 1 !important;
  }

  .v-card-title {
    font-size: 18px !important;
  }

  .v-window {
    &-item {
      padding: 20px;
    }
  }
}
</style>
